.TH "Q:/@websites@/coop/labs/dev2/class/auth/auth_rest_curl.php" 3 "Wed Jul 17 2013" "Version 4.11" "Xortify Honeypot PHP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Q:/@websites@/coop/labs/dev2/class/auth/auth_rest_curl.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBXortifyAuthRest_Curl\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP(!function_exists('json_encode')) 
.br
\fBif\fP(!function_exists('json_decode')) 
.br
\fBif\fP(!defined('XORTIFY_REST_API')) 
.br
define('XORTIFY_REST_API' \fB_RUN_XORTIFY_API_REST\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBif\fP (!function_exists('json_encode')) \fBif\fP (!function_exists('json_decode')) \fBif\fP (!defined('XORTIFY_REST_API')) define('XORTIFY_REST_API' _RUN_XORTIFY_API_REST"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot PHP Library from the source code\&.
