.TH "core" 3 "Wed Jul 17 2013" "Version 4.11" "Xortify Honeypot PHP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Abstract class for storage engine for caching
.PP
cache 
.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot PHP Library from the source code\&.
