.TH "Q:/@websites@/coop/labs/dev2/providers/xortify/footer.post.loader.php" 3 "Wed Jul 17 2013" "Version 4.11" "Xortify Honeypot PHP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Q:/@websites@/coop/labs/dev2/providers/xortify/footer.post.loader.php \- 
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot PHP Library from the source code\&.
