.TH "Q:/@websites@/coop/labs/dev2/poll/index.php" 3 "Wed Jul 17 2013" "Version 4.11" "Xortify Honeypot PHP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Q:/@websites@/coop/labs/dev2/poll/index.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP (\fBxortify_validateToken\fP($_REQUEST['token'], true, 'poll_token')==true)"
.br
.ti -1c
.RI "\fBexit\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "exit"

.SS "if(\fBxortify_validateToken\fP($_REQUEST['token'], true, 'poll_token')==true)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot PHP Library from the source code\&.
