.TH "Q:/@websites@/coop/labs/dev2/class/wgetserialised.php" 3 "Wed Jul 17 2013" "Version 4.11" "Xortify Honeypot PHP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Q:/@websites@/coop/labs/dev2/class/wgetserialised.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWGETSERIALISEDXortifyExchange\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP(!defined('XORTIFY_SERIAL_API')) 
.br
define('XORTIFY_SERIAL_API' \fB_RUN_XORTIFY_API_SERIAL\fP"
.br
.ti -1c
.RI "const \fBXOOPS_SERIAL_LIB\fP 'PHPSERIAL'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBif\fP (!defined('XORTIFY_SERIAL_API')) define('XORTIFY_SERIAL_API' _RUN_XORTIFY_API_SERIAL"

.SS "const XOOPS_SERIAL_LIB 'PHPSERIAL'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot PHP Library from the source code\&.
