.TH "E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/language/english/admin.php" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/language/english/admin.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fB_XS_IPTYPE_IP4\fP 'IPv4'"
.br
.ti -1c
.RI "const \fB_XS_IPTYPE_IP6\fP 'IPv6'"
.br
.ti -1c
.RI "const \fB_XS_IPTYPE_EMPTY\fP 'No IP'"
.br
.ti -1c
.RI "const \fB_XS_AM_IPTYPE\fP 'IP Type'"
.br
.ti -1c
.RI "const \fB_XS_AM_IPADDRESS\fP 'IP Address'"
.br
.ti -1c
.RI "const \fB_XS_AM_NETADDRESS\fP 'Network Address'"
.br
.ti -1c
.RI "const \fB_XS_AM_PROXYIP\fP 'Proxy IP'"
.br
.ti -1c
.RI "const \fB_XS_AM_MACADDRESS\fP 'Mac Address'"
.br
.ti -1c
.RI "const \fB_XS_AM_LONG\fP 'Network Pointer'"
.br
.ti -1c
.RI "const \fB_XS_AM_BANS\fP 'Current Network Bans'"
.br
.ti -1c
.RI "const \fB_XS_AM_NOCACHEMSG\fP '<center><font size='+2'>EMPTY BAN CACHE!! NOTHING TO DISPLAY!!</font></center>'"
.br
.ti -1c
.RI "const \fB_XOR_AM_LOG_H1\fP 'Xortify Usage Log'"
.br
.ti -1c
.RI "const \fB_XOR_AM_LOG_P\fP 'This is the actions that have occured on your system in the last period up unto the log drop date!'"
.br
.ti -1c
.RI "const \fB_XOR_AM_TH_ACTION\fP 'Action'"
.br
.ti -1c
.RI "const \fB_XOR_AM_TH_PROVIDER\fP 'Provider'"
.br
.ti -1c
.RI "const \fB_XOR_AM_TH_DATE\fP 'Date'"
.br
.ti -1c
.RI "const \fB_XOR_AM_TH_UNAME\fP 'Username'"
.br
.ti -1c
.RI "const \fB_XOR_AM_TH_EMAIL\fP 'Email'"
.br
.ti -1c
.RI "const \fB_XOR_AM_TH_IP4\fP 'Ip4'"
.br
.ti -1c
.RI "const \fB_XOR_AM_TH_IP6\fP 'IP6'"
.br
.ti -1c
.RI "const \fB_XOR_AM_TH_PROXY_IP4\fP 'Proxy IP4'"
.br
.ti -1c
.RI "const \fB_XOR_AM_TH_PROXY_IP6\fP 'Proxy IP6'"
.br
.ti -1c
.RI "const \fB_XOR_AM_TH_NETWORK_ADDY\fP 'Netbios Address'"
.br
.ti -1c
.RI "const \fB_XOR_AM_TH_AGENT\fP 'User Agent'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_COUNTS\fP 'Log Action and Counts'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_THEREARE_BANNED\fP 'Banned Individuals:&nbsp;%s'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_THEREARE_BLOCKED\fP 'Blocked Individuals:&nbsp;%s'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_THEREARE_MONITORED\fP 'Monitored Individuals:&nbsp;%s'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_THEREARE_PROJECTHONEYPOTORG\fP 'Individuals or bots picked up by ProjectHoneypot\&.org:&nbsp;%s'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_THEREARE_PROTECTOR\fP 'Individuals or bots picked up by Protector Module:&nbsp;%s'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_THEREARE_SPIDERS\fP 'Individuals or bots picked up by Spiders Module:&nbsp;%s'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_THEREARE_STOPFORUMSPAMCOM\fP 'Individuals or bots picked up by StopForumSpam\&.com:&nbsp;%s'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_THEREARE_XORTIFY\fP 'Individuals or bots picked up by Xortify Cloud:&nbsp;%s'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_THEREARE_CLOUDEDBANS\fP 'Clouded Bans Loaded from Xortify Cloud:&nbsp;%s'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_MAKEDONATE\fP 'Make Donation to Further Xortify!'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_NONETWORKCOMM_DISCLAIMER\fP 'The current URI is unaccessable on the selected protocol\&. This could mean you are either missing a required PHP Extension or have a firewall blocking port 80 to the Xortify Cloud\&.<br/><br/><strong>You can try changing the protocol selected in preferences to see \fBif\fP this may elivate the communication fawl of your hosting services\&.</strong>'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_ERROR_OCCURED\fP 'Error Occured Communicating with cloud'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_ERROR_URL\fP 'URL/URI Being Contacted'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_ERROR_PROTOCOL\fP 'Protocol Being Used'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_SIGNUP_XORTIFY_H2\fP 'Signup to the XOOPS fortification cloud'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_SIGNUP_XORTIFY_P\fP 'Here you can signup to the XOOPS fortification cloud called Xortify, the main node for this cloud is featured at http://xortify\&.com but there can be other nodes, this will prevent spam signup, website harvesting, and general hacking of your site\&.<br/><br/>It will also share the IP\\'s of Bad IP Highlighted by Protector with other people running Xortify\&.'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_SIGNUP_XORTIFY_FORM_TD2\fP 'Sign-up this Website\\'s User Account on the Xortify Cloud\&.'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_THEREARE_WHENCLEANED\fP 'Xortify File Cache Cleaned Last: %s'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_THEREARE_CLEANINGTOOK\fP 'Xortify File Cache Cleaning Took: %s seconds'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_THEREARE_FILESDELETED\fP 'Xortify Cache Files Deleted: %s'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_THEREARE_BYTESSAVED\fP 'Xortify Cache Cleaning Saved: %s bytes'"
.br
.ti -1c
.RI "const \fB_XS_AM_CATEGORY\fP 'Ban Category'"
.br
.ti -1c
.RI "const \fB_XS_AM_BANID\fP 'Ban Id:'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_ABOUT_CHANGELOG\fP 'Change log'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_ABOUT_DESCRIPTION\fP 'Description'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_ABOUT_MODULEINFO\fP 'Module Info'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_ABOUT_MODULESTATUS\fP 'Status:'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_ABOUT_UPDATEDATE\fP 'Update date:'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_ABOUT_WEBSITE\fP 'Website:'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_KEYS\fP 'System Keys'"
.br
.ti -1c
.RI "const \fB_XOR_ADMIN_INSTANCE_KEY\fP 'Xortify Local Instance Key: %s'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const _XOR_ADMIN_ABOUT_CHANGELOG 'Change log'"

.SS "const _XOR_ADMIN_ABOUT_DESCRIPTION 'Description'"

.SS "const _XOR_ADMIN_ABOUT_MODULEINFO 'Module Info'"

.SS "const _XOR_ADMIN_ABOUT_MODULESTATUS 'Status:'"

.SS "const _XOR_ADMIN_ABOUT_UPDATEDATE 'Update date:'"

.SS "const _XOR_ADMIN_ABOUT_WEBSITE 'Website:'"

.SS "const _XOR_ADMIN_COUNTS 'Log Action and Counts'"

.SS "const _XOR_ADMIN_ERROR_OCCURED 'Error Occured Communicating with cloud'"

.SS "const _XOR_ADMIN_ERROR_PROTOCOL 'Protocol Being Used'"

.SS "const _XOR_ADMIN_ERROR_URL 'URL/URI Being Contacted'"

.SS "const _XOR_ADMIN_INSTANCE_KEY 'Xortify Local Instance Key: %s'"

.SS "const _XOR_ADMIN_KEYS 'System Keys'"

.SS "const _XOR_ADMIN_MAKEDONATE 'Make Donation to Further Xortify!'"

.SS "const _XOR_ADMIN_NONETWORKCOMM_DISCLAIMER 'The current URI is unaccessable on the selected protocol\&. This could mean you are either missing a required PHP Extension or have a firewall blocking port 80 to the Xortify Cloud\&.<br/><br/><strong>You can try changing the protocol selected in preferences to see \fBif\fP this may elivate the communication fawl of your hosting services\&.</strong>'"

.SS "const _XOR_ADMIN_SIGNUP_XORTIFY_FORM_TD2 'Sign-up this Website\\'s User Account on the Xortify Cloud\&.'"

.SS "const _XOR_ADMIN_SIGNUP_XORTIFY_H2 'Signup to the XOOPS fortification cloud'"

.SS "const _XOR_ADMIN_SIGNUP_XORTIFY_P 'Here you can signup to the XOOPS fortification cloud called Xortify, the main node for this cloud is featured at http://xortify\&.com but there can be other nodes, this will prevent spam signup, website harvesting, and general hacking of your site\&.<br/><br/>It will also share the IP\\'s of Bad IP Highlighted by Protector with other people running Xortify\&.'"

.SS "const _XOR_ADMIN_THEREARE_BANNED 'Banned Individuals:&nbsp;%s'"

.SS "const _XOR_ADMIN_THEREARE_BLOCKED 'Blocked Individuals:&nbsp;%s'"

.SS "const _XOR_ADMIN_THEREARE_BYTESSAVED 'Xortify Cache Cleaning Saved: %s bytes'"

.SS "const _XOR_ADMIN_THEREARE_CLEANINGTOOK 'Xortify File Cache Cleaning Took: %s seconds'"

.SS "const _XOR_ADMIN_THEREARE_CLOUDEDBANS 'Clouded Bans Loaded from Xortify Cloud:&nbsp;%s'"

.SS "const _XOR_ADMIN_THEREARE_FILESDELETED 'Xortify Cache Files Deleted: %s'"

.SS "const _XOR_ADMIN_THEREARE_MONITORED 'Monitored Individuals:&nbsp;%s'"

.SS "const _XOR_ADMIN_THEREARE_PROJECTHONEYPOTORG 'Individuals or bots picked up by ProjectHoneypot\&.org:&nbsp;%s'"

.SS "const _XOR_ADMIN_THEREARE_PROTECTOR 'Individuals or bots picked up by Protector Module:&nbsp;%s'"

.SS "const _XOR_ADMIN_THEREARE_SPIDERS 'Individuals or bots picked up by Spiders Module:&nbsp;%s'"

.SS "const _XOR_ADMIN_THEREARE_STOPFORUMSPAMCOM 'Individuals or bots picked up by StopForumSpam\&.com:&nbsp;%s'"

.SS "const _XOR_ADMIN_THEREARE_WHENCLEANED 'Xortify File Cache Cleaned Last: %s'"

.SS "const _XOR_ADMIN_THEREARE_XORTIFY 'Individuals or bots picked up by Xortify Cloud:&nbsp;%s'"

.SS "const _XOR_AM_LOG_H1 'Xortify Usage Log'"

.SS "const _XOR_AM_LOG_P 'This is the actions that have occured on your system in the last period up unto the log drop date!'"

.SS "const _XOR_AM_TH_ACTION 'Action'"

.SS "const _XOR_AM_TH_AGENT 'User Agent'"

.SS "const _XOR_AM_TH_DATE 'Date'"

.SS "const _XOR_AM_TH_EMAIL 'Email'"

.SS "const _XOR_AM_TH_IP4 'Ip4'"

.SS "const _XOR_AM_TH_IP6 'IP6'"

.SS "const _XOR_AM_TH_NETWORK_ADDY 'Netbios Address'"

.SS "const _XOR_AM_TH_PROVIDER 'Provider'"

.SS "const _XOR_AM_TH_PROXY_IP4 'Proxy IP4'"

.SS "const _XOR_AM_TH_PROXY_IP6 'Proxy IP6'"

.SS "const _XOR_AM_TH_UNAME 'Username'"

.SS "const _XS_AM_BANID 'Ban Id:'"

.SS "const _XS_AM_BANS 'Current Network Bans'"

.SS "const _XS_AM_CATEGORY 'Ban Category'"

.SS "const _XS_AM_IPADDRESS 'IP Address'"

.SS "const _XS_AM_IPTYPE 'IP Type'"

.SS "const _XS_AM_LONG 'Network Pointer'"

.SS "const _XS_AM_MACADDRESS 'Mac Address'"

.SS "const _XS_AM_NETADDRESS 'Network Address'"

.SS "const _XS_AM_NOCACHEMSG '<center><font size='+2'>EMPTY BAN CACHE!! NOTHING TO DISPLAY!!</font></center>'"

.SS "const _XS_AM_PROXYIP 'Proxy IP'"

.SS "const _XS_IPTYPE_EMPTY 'No IP'"

.SS "const _XS_IPTYPE_IP4 'IPv4'"

.SS "const _XS_IPTYPE_IP6 'IPv6'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
