.TH "E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/class/auth/auth_minimumcloud.php" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/class/auth/auth_minimumcloud.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBXortifyAuthMinimumCloud\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "foreach(get_loaded_extensions() 
.br
as $ext) if($nativecurl==true) \fBif\fP (!defined('XOOPS_MINIMUMCLOUD_LIB')) define('XOOPS_MINIMUMCLOUD_LIB' = Xoops::getInstance()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "if = Xoops::getInstance()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
