.TH "E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/class/auth/auth_soap.php" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/class/auth/auth_soap.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBXortifyAuthSoap\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP(!file_exists(XOOPS_ROOT_PATH\&.'/class/soap/xoopssoap\&.php')) \fBelse\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBif\fP (!file_exists(XOOPS_ROOT_PATH\&.'/class/soap/xoopssoap\&.php')) else"
\fBInitial value:\fP
.PP
.nf
{
    require_once (XOOPS_ROOT_PATH\&.'/class/soap/xoopssoap\&.php')
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
