.TH "class" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
class \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
XOOPS form element of dhtmltextarea
.PP
\fBCopyright:\fP
.RS 4
The XOOPS Project http://sourceforge.net/projects/xoops/  GNU GPL 2 (http://www.gnu.org/licenses/old-licenses/gpl-2.0.html)
.RE
.PP
xoopsform 
.PP
\fBSince:\fP
.RS 4
2\&.0\&.0 
.RE
.PP
\fBAuthor:\fP
.RS 4
Kazumi Ono (AKA onokazu) http://www.myweb.ne.jp/, http://jp.xoops.org/ 
.PP
Taiwen Jiang phppp@users.sourceforge.net 
.PP
Vinod smartvinu@gmail.com 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBId:\fP
.RS 4
\fBformdhtmltextarea\&.php\fP 9392 2012-04-27 21:49:29Z mageg 
.RE
.PP
.PP
XOOPS Form element of editor
.PP
\fBCopyright:\fP
.RS 4
The XOOPS Project http://sourceforge.net/projects/xoops/  GNU GPL 2 (http://www.gnu.org/licenses/old-licenses/gpl-2.0.html)
.RE
.PP
xoopsform 
.PP
\fBSince:\fP
.RS 4
2\&.0\&.0 
.RE
.PP
\fBAuthor:\fP
.RS 4
Taiwen Jiang phppp@users.sourceforge.net 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBId:\fP
.RS 4
\fBformeditor\&.php\fP 8271 2011-11-11 19:46:00Z trabis 
.RE
.PP
.PP
XOOPS form element of text area
.PP
\fBCopyright:\fP
.RS 4
The XOOPS Project http://sourceforge.net/projects/xoops/  GNU GPL 2 (http://www.gnu.org/licenses/old-licenses/gpl-2.0.html)
.RE
.PP
xoopsform 
.PP
\fBSince:\fP
.RS 4
2\&.0\&.0 
.RE
.PP
\fBAuthor:\fP
.RS 4
Kazumi Ono (AKA onokazu) http://www.myweb.ne.jp/, http://jp.xoops.org/ 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBId:\fP
.RS 4
\fBformtextarea\&.php\fP 9392 2012-04-27 21:49:29Z mageg 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
