.TH "E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/plugin Directory Reference" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/plugin Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBprojecthoneypot\&.org\&.php\fP"
.br
.ti -1c
.RI "file \fBprotector\&.php\fP"
.br
.ti -1c
.RI "file \fBspiders\&.php\fP"
.br
.ti -1c
.RI "file \fBstopforumspam\&.com\&.php\fP"
.br
.ti -1c
.RI "file \fBxortify\&.php\fP"
.br
.in -1c
