.TH "E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs Directory Reference" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBclass\fP"
.br
.ti -1c
.RI "directory \fBmodules\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbanned\&.php\fP"
.br
.in -1c
