.TH "E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/poll/index.php" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/poll/index.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "global \fB$xoops\fP"
.br
.ti -1c
.RI "global \fB$xoopsPreload\fP"
.br
.ti -1c
.RI "global \fB$xoopsLogger\fP"
.br
.ti -1c
.RI "global \fB$xoopsErrorHandler\fP"
.br
.ti -1c
.RI "global \fB$xoopsSecurity\fP"
.br
.ti -1c
.RI "global \fB$sess_handler\fP"
.br
.ti -1c
.RI "\fB$xoopsOption\fP ['nocommon'] =false"
.br
.ti -1c
.RI "\fBif\fP ($GLOBALS['xoopsSecurity']->validateToken($_REQUEST['token'], true, 'poll_token')==true)"
.br
.ti -1c
.RI "\fBexit\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "global $sess_handler"

.SS "global $xoops"

.SS "global $xoopsErrorHandler"

.SS "global $xoopsLogger"

.SS "$xoopsOption['nocommon'] =false"

.SS "global $xoopsPreload"

.SS "global $xoopsSecurity"

.SS "exit"

.SS "if($GLOBALS['xoopsSecurity']->validateToken($_REQUEST['token'], true, 'poll_token')==true)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
