.TH "E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/admin/menu.php" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/admin/menu.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "global \fB$adminmenu\fP = array()"
.br
.ti -1c
.RI "\fB$xortifyImageAdmin\fP = '\&.\&./\&.\&./\&.\&./\&.\&./\&.\&./modules/xortify/images/icons/32'"
.br
.ti -1c
.RI "\fB$adminmenu\fP [1]['title'] = \fB_XOR_ADMENU4\fP"
.br
.ti -1c
.RI "\fB$adminmenu\fP [1]['icon'] = 'home\&.png'"
.br
.ti -1c
.RI "\fB$adminmenu\fP [1]['image'] = 'home\&.png'"
.br
.ti -1c
.RI "\fB$adminmenu\fP [1]['link'] = 'admin/index\&.php?op=dashboard'"
.br
.ti -1c
.RI "\fB$adminmenu\fP [2]['title'] = \fB_XOR_ADMENU1\fP"
.br
.ti -1c
.RI "\fB$adminmenu\fP [2]['icon'] = $xortifyImageAdmin\&.'/current\&.bans\&.png'"
.br
.ti -1c
.RI "\fB$adminmenu\fP [2]['image'] = $xortifyImageAdmin\&.'/current\&.bans\&.png'"
.br
.ti -1c
.RI "\fB$adminmenu\fP [2]['link'] = 'admin/index\&.php?op=list&fct=bans'"
.br
.ti -1c
.RI "\fB$adminmenu\fP [3]['title'] = \fB_XOR_ADMENU3\fP"
.br
.ti -1c
.RI "\fB$adminmenu\fP [3]['icon'] = $xortifyImageAdmin\&.'/xortify\&.log\&.png'"
.br
.ti -1c
.RI "\fB$adminmenu\fP [3]['image'] = $xortifyImageAdmin\&.'/xortify\&.log\&.png'"
.br
.ti -1c
.RI "\fB$adminmenu\fP [3]['link'] = 'admin/index\&.php?op=log'"
.br
.ti -1c
.RI "\fB$adminmenu\fP [4]['title'] = \fB_XOR_ADMENU2\fP"
.br
.ti -1c
.RI "\fB$adminmenu\fP [4]['icon'] = $xortifyImageAdmin\&.'/access\&.list\&.png'"
.br
.ti -1c
.RI "\fB$adminmenu\fP [4]['image'] = $xortifyImageAdmin\&.'/access\&.list\&.png'"
.br
.ti -1c
.RI "\fB$adminmenu\fP [4]['link'] = 'admin/index\&.php?op=signup&fct=signup'"
.br
.ti -1c
.RI "\fB$adminmenu\fP [5]['title'] = \fB_XOR_ADMENU5\fP"
.br
.ti -1c
.RI "\fB$adminmenu\fP [5]['icon'] = 'about\&.png'"
.br
.ti -1c
.RI "\fB$adminmenu\fP [5]['image'] = 'about\&.png'"
.br
.ti -1c
.RI "\fB$adminmenu\fP [5]['link'] = 'admin/index\&.php?op=about'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$adminmenu = array()"

.SS "$adminmenu[1]['title'] = \fB_XOR_ADMENU4\fP"

.SS "$adminmenu[1]['icon'] = 'home\&.png'"

.SS "$adminmenu[1]['image'] = 'home\&.png'"

.SS "$adminmenu[1]['link'] = 'admin/index\&.php?op=dashboard'"

.SS "$adminmenu[2]['title'] = \fB_XOR_ADMENU1\fP"

.SS "$adminmenu[2]['icon'] = $xortifyImageAdmin\&.'/current\&.bans\&.png'"

.SS "$adminmenu[2]['image'] = $xortifyImageAdmin\&.'/current\&.bans\&.png'"

.SS "$adminmenu[2]['link'] = 'admin/index\&.php?op=list&fct=bans'"

.SS "$adminmenu[3]['title'] = \fB_XOR_ADMENU3\fP"

.SS "$adminmenu[3]['icon'] = $xortifyImageAdmin\&.'/xortify\&.log\&.png'"

.SS "$adminmenu[3]['image'] = $xortifyImageAdmin\&.'/xortify\&.log\&.png'"

.SS "$adminmenu[3]['link'] = 'admin/index\&.php?op=log'"

.SS "$adminmenu[4]['title'] = \fB_XOR_ADMENU2\fP"

.SS "$adminmenu[4]['icon'] = $xortifyImageAdmin\&.'/access\&.list\&.png'"

.SS "$adminmenu[4]['image'] = $xortifyImageAdmin\&.'/access\&.list\&.png'"

.SS "$adminmenu[4]['link'] = 'admin/index\&.php?op=signup&fct=signup'"

.SS "$adminmenu[5]['title'] = \fB_XOR_ADMENU5\fP"

.SS "$adminmenu[5]['icon'] = 'about\&.png'"

.SS "$adminmenu[5]['image'] = 'about\&.png'"

.SS "$adminmenu[5]['link'] = 'admin/index\&.php?op=about'"

.SS "$xortifyImageAdmin = '\&.\&./\&.\&./\&.\&./\&.\&./\&.\&./modules/xortify/images/icons/32'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
