.TH "E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/class/minimumcloud.php" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/class/minimumcloud.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMinimumcloudXortifyExchange\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP(!function_exists('json_encode')) 
.br
\fBif\fP(!function_exists('json_decode')) 
.br
foreach(get_loaded_extensions() 
.br
as $ext) \fB$GLOBALS\fP ['xoops'] = Xoops::getInstance()"
.br
.ti -1c
.RI "if($nativecurl==true) \fBif\fP (!defined('XOOPS_MINIMUMCLOUD_LIB')) define('XOOPS_MINIMUMCLOUD_LIB'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBif\fP (!function_exists('json_encode')) \fBif\fP (!function_exists('json_decode')) foreach (get_loaded_extensions() as $ext) $GLOBALS['xoops'] = Xoops::getInstance()"

.SS "if ($nativecurl==true) if(!defined('XOOPS_MINIMUMCLOUD_LIB')) define('XOOPS_MINIMUMCLOUD_LIB'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
