.TH "E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/language/english/modinfo.php" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/language/english/modinfo.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fB_MI_XOR_DESC\fP 'Xortify - Sector Network Security - Fortify your XOOPS'"
.br
.ti -1c
.RI "const \fB_MI_XOR_CREDITS\fP 'GI-JOE (Protector), WISHCRAFT, Trabis'"
.br
.ti -1c
.RI "const \fB_XOR_MI_USERNAME\fP 'Xortify Cloud Username'"
.br
.ti -1c
.RI "const \fB_XOR_MI_USERNAME_DESC\fP 'You can get one of these by going to the menu <a href=''\&.XOOPS_URL\&.'/modules/xortify/admin/index\&.php?op=signup&fct=signup'>Sign-up</a>'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PASSWORD\fP 'Xortify Cloud Password'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PASSWORD_DESC\fP 'You assign one of these by going to the menu <a href=''\&.XOOPS_URL\&.'/modules/xortify/admin/index\&.php?op=signup&fct=signup'>Sign-up</a>'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS\fP 'Seconds to base Cache List on!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_DESC\fP 'Period of time for ban list to be invocated!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROVIDERS\fP 'Provider Plug-ins'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROVIDERS_DESC\fP 'Provider\\'s that are supported by Xortify'"
.br
.ti -1c
.RI "const \fB_XOR_ADMENU1\fP 'Ban List'"
.br
.ti -1c
.RI "const \fB_XOR_ADMENU2\fP 'Sign-up'"
.br
.ti -1c
.RI "const \fB_XOR_ADMENU3\fP 'Usage Logs'"
.br
.ti -1c
.RI "const \fB_XOR_FRM_TITLE\fP 'Sign-up to Xortify\&.com - Fortify your XOOPS'"
.br
.ti -1c
.RI "const \fB_XOR_FRM_UNAME\fP 'Your Xortify Username'"
.br
.ti -1c
.RI "const \fB_XOR_FRM_EMAIL\fP 'Your Email Address'"
.br
.ti -1c
.RI "const \fB_XOR_FRM_PASS\fP 'Your Password'"
.br
.ti -1c
.RI "const \fB_XOR_FRM_VPASS\fP 'Validate Your Password'"
.br
.ti -1c
.RI "const \fB_XOR_FRM_URL\fP 'Your Primary URL'"
.br
.ti -1c
.RI "const \fB_XOR_FRM_VIEWEMAIL\fP 'View Your Email'"
.br
.ti -1c
.RI "const \fB_XOR_FRM_TIMEZONE\fP 'Your Timezone'"
.br
.ti -1c
.RI "const \fB_XOR_FRM_DISCLAIMER\fP 'Xortify Disclaimer'"
.br
.ti -1c
.RI "const \fB_XOR_FRM_DISCLAIMER_AGREE\fP 'Agree to Xortify Disclaimer'"
.br
.ti -1c
.RI "const \fB_XOR_FRM_PUZZEL\fP 'Solve Puzzel'"
.br
.ti -1c
.RI "const \fB_XOR_FRM_REGISTER\fP 'Register with Xortify\&.com'"
.br
.ti -1c
.RI "const \fB_XOR_USERCREATED_PLEASEACTIVATE\fP 'Check Your Email for Activation Email, Click on the activation link to activate module!'"
.br
.ti -1c
.RI "const \fB_XOR_FRM_NOSOAP_DISCLAIMER\fP '<strong>There is no API Communication with Xortify\&.com check you have PHP \fBSOAP\fP installed as an extension and you have no firewalls preventing normal \fBSOAP\fP Protocol Communication\&. You will not be able to continue until this message has been replaced with the Xortify Disclaimer\&.<br/><br/>The Submit button below will appear when this is working, xortify is currently <strong>Offline</strong>'"
.br
.ti -1c
.RI "const \fB_XOR_MI_RECORDS\fP 'Records to Retrieve!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_RECORDS_DESC\fP 'Number of total records to retrieve!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_37600\fP '5 Hours'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_28800\fP '4 Hours'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_14400\fP '3 Hours'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_7200\fP '2 Hours'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_3600\fP '1 Hour'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_1800\fP '30 minutes'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_1200\fP '20 minutes'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_600\fP '10 minutes'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_300\fP '5 Minutes'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_180\fP '3 Minutes'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_60\fP '1 Minute'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_30\fP '30 Seconds'"
.br
.ti -1c
.RI "const \fB_XOR_MI_RECORDS_177600\fP '177600 Records'"
.br
.ti -1c
.RI "const \fB_XOR_MI_RECORDS_48800\fP '48800 Records'"
.br
.ti -1c
.RI "const \fB_XOR_MI_RECORDS_24400\fP '24400 Records'"
.br
.ti -1c
.RI "const \fB_XOR_MI_RECORDS_12200\fP '12200 Records'"
.br
.ti -1c
.RI "const \fB_XOR_MI_RECORDS_3600\fP '3600 Records'"
.br
.ti -1c
.RI "const \fB_XOR_MI_RECORDS_1800\fP '1800 Records'"
.br
.ti -1c
.RI "const \fB_XOR_MI_RECORDS_1200\fP '1200 Records'"
.br
.ti -1c
.RI "const \fB_XOR_MI_RECORDS_600\fP '600 Records'"
.br
.ti -1c
.RI "const \fB_XOR_MI_RECORDS_300\fP '300 Records'"
.br
.ti -1c
.RI "const \fB_XOR_MI_RECORDS_180\fP '180 Records'"
.br
.ti -1c
.RI "const \fB_XOR_MI_RECORDS_60\fP '60 Records'"
.br
.ti -1c
.RI "const \fB_XOR_MI_RECORDS_30\fP '30 Records'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROVIDER_XORTIFY\fP 'Xortify Module'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROVIDER_PROTECTOR\fP 'Protector Module'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROVIDER_STOPFORUMSPAM\fP 'Stop Forum Spam'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROVIDER_SPIDERS\fP 'Spiders Module'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROVIDER_PROJECTHONEYPOT\fP 'Project Honeypot'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROTOCOL\fP 'Cloud Communication Protocol'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROTOCOL_DESC\fP 'This is the protocol that is used in the communication with the xortify cloud!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROTOCOL_SOAP\fP '\fBSOAP\fP Protocol'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROTOCOL_CURL\fP '\fBCURL\fP Protocol'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROTOCOL_JSON\fP 'Open Access Protocol'"
.br
.ti -1c
.RI "const \fB_XOR_MI_URISOAP\fP '\fBSOAP\fP Cloud Base URL'"
.br
.ti -1c
.RI "const \fB_XOR_MI_URISOAP_DESC\fP 'This is the URL for \fBSOAP\fP Communication (With Trailing Slash)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_URICURL\fP '\fBCURL\fP Cloud Base URL'"
.br
.ti -1c
.RI "const \fB_XOR_MI_URICURL_DESC\fP 'This is the URL for \fBCURL\fP \fBJSON\fP Communication (With Trailing Slash)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_URIJSON\fP 'Open Access Cloud Base URL'"
.br
.ti -1c
.RI "const \fB_XOR_MI_URIJSON_DESC\fP 'This is the URL for wGET \fBJSON\fP (With Trailing Slash)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PHP_DAYS\fP '%s day(s)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PHP_NUMBEROFDAYS\fP '<a href='http://www\&.projecthoneypot\&.org'>Project Honeypot</a> - Last Number of Days Seen'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PHP_NUMBEROFDAYS_DESC\fP 'This is the number of days upto that the IP has been seen and flagged by project honeypot'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PHP_SEVERITY\fP '%s percent'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PHP_SEVERITYLEVEL\fP '<a href='http://www\&.projecthoneypot\&.org'>Project Honeypot</a> - Severity Level of IP'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PHP_SEVERITYLEVEL_DESC\fP 'This is the severity level on the honeypot that the IP has been seen and flagged by project honeypot'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PHP_SCANMODE\fP '<a href='http://www\&.projecthoneypot\&.org'>Project Honeypot</a> - What will be banned'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PHP_SCANMODE_DESC\fP 'This list is in a hierachy which will ban from what you select and down in the list from severity\&.'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PHP_SCANMODE_SUSPICIOUS\fP 'Suspicious IP'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PHP_SCANMODE_HARVESTER\fP 'Harvester IP'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PHP_SCANMODE_SUSICIOUSHARVESTER\fP 'Suspicious + Harvester IP'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PHP_SCANMODE_SPAMMER\fP 'Comment Spammer'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PHP_SCANMODE_SUSPICIOUSSPAMMER\fP 'Suspicious + Comment Spammer'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PHP_SCANMODE_HARVESTERSPAMMER\fP 'Harvester + Comment Spammer'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PHP_SCANMODE_SUSPICIOUSHARVESTERSPAMMER\fP 'Suspicious + Harvester + Comment Spammer'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_EMAIILFREQ\fP 'Occured %s time(s)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_EMAILFREQUENCY\fP '<a href='http://www\&.stopforumspam\&.com'>Stop Forum Spam</a> - Number of time email address has been reported'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_EMAILFREQUENCY_DESC\fP 'This is the number of time the email has been reported as spam and will ban the IP and details when it occurs at this level\&.'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_UNAMEFREQ\fP 'Occured %s time(s)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_UNAMEFREQUENCY\fP '<a href='http://www\&.stopforumspam\&.com'>Stop Forum Spam</a> - Number of time username has been reported'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_UNAMEFREQUENCY_DESC\fP 'This is the number of time the username has been reported as spam and will ban the IP and details when it occurs at this level\&.'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_IPFREQ\fP 'Occured %s time(s)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_IPFREQUENCY\fP '<a href='http://www\&.stopforumspam\&.com'>Stop Forum Spam</a> - Number of time IP address has been reported'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_IPFREQUENCY_DESC\fP 'This is the number of time the IP Address has been reported as spam and will ban the IP and details when it occurs at this level\&.'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_EMAILLASTSEEN\fP '<a href='http://www\&.stopforumspam\&.com'>Stop Forum Spam</a> - How long ago the email address was seen'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_EMAILLASTSEEN_DESC\fP 'This is the period of time allocated to wence the email was last seen, \fBif\fP it occured after this period it will not be banned!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_UNAMELASTSEEN\fP '<a href='http://www\&.stopforumspam\&.com'>Stop Forum Spam</a> - How long ago the username was seen'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_UNAMELASTSEEN_DESC\fP 'This is the period of time allocated to wence the username was last seen, \fBif\fP it occured after this period it will not be banned!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_IPLASTSEEN\fP '<a href='http://www\&.stopforumspam\&.com'>Stop Forum Spam</a> - How long ago the IP address was seen'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_IPLASTSEEN_DESC\fP 'This is the period of time allocated to wence the IP address was last seen, \fBif\fP it occured after this period it will not be banned!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_LASTSEEN_24HOURS\fP '24 Hours'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_LASTSEEN_1WEEK\fP '1 Week'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_LASTSEEN_FORTNIGHT\fP 'A Fortnight'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_LASTSEEN_1MONTH\fP '1 Month'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_LASTSEEN_2MONTHS\fP '2 Months'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_LASTSEEN_3MONTHS\fP '3 Months'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_LASTSEEN_4MONTHS\fP '4 Months'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_LASTSEEN_5MONTHS\fP '5 Months'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_LASTSEEN_6MONTHS\fP '6 Months'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_LASTSEEN_12MONTHS\fP '1 Year'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_LASTSEEN_24MONTHS\fP '2 Years'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SFS_LASTSEEN_36MONTHS\fP '3 Years'"
.br
.ti -1c
.RI "const \fB_XOR_MI_LOG_BANNED\fP 'Log Banned Action'"
.br
.ti -1c
.RI "const \fB_XOR_MI_LOG_BANNED_DESC\fP 'When Xortify Bans something on the cloud, then log it!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_LOG_BLOCKED\fP 'Log Blocked Action'"
.br
.ti -1c
.RI "const \fB_XOR_MI_LOG_BLOCKED_DESC\fP 'When Xortify Blocks something as detected on the cloud, then log it!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_LOG_MONITORED\fP 'Log Monitored Action'"
.br
.ti -1c
.RI "const \fB_XOR_MI_LOG_MONITORED_DESC\fP 'When Xortify Monitor\\'s something/someone as detected on the cloud, then log it!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_LOGDROPS\fP 'Log Deletes Itself After'"
.br
.ti -1c
.RI "const \fB_XOR_MI_LOGDROPS_DESC\fP 'This is how long the log stays on your site for after a record reaches this age it is deleted!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_URISERIAL\fP 'Serilisation Cloud Base URL'"
.br
.ti -1c
.RI "const \fB_XOR_MI_URISERIAL_DESC\fP 'This is the URL for Serialisation Communication in cURL or wGET (With Trailing Slash)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_URIXML\fP '\fBXML\fP Cloud Base URL'"
.br
.ti -1c
.RI "const \fB_XOR_MI_URIXML_DESC\fP 'This is the URL for cURL or wGET for \fBXML\fP Communication (With Trailing Slash)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_IPCACHE\fP 'IP Cache Time'"
.br
.ti -1c
.RI "const \fB_XOR_MI_IPCACHE_DESC\fP 'This is the amount of time an IP Address and information on it is cached!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_29030400\fP '1 Year'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_14515200\fP '6 Months'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_7257600\fP '3 Months'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_2419200\fP '1 Month'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_1209600\fP '1 Fortnight'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_604800\fP '1 Week'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_86400\fP '24 Hours'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SECONDS_43200\fP '12 Hours'"
.br
.ti -1c
.RI "const \fB_XOR_MI_CRONTYPE\fP 'Type of cron scheduling'"
.br
.ti -1c
.RI "const \fB_XOR_MI_CRONTYPE_DESC\fP 'This is the type of scheduling system you are using for your cron job'"
.br
.ti -1c
.RI "const \fB_XOR_MI_CRONTYPE_PRELOADER\fP 'Preloader'"
.br
.ti -1c
.RI "const \fB_XOR_MI_CRONTYPE_CRONTAB\fP 'UNIX Cron Job'"
.br
.ti -1c
.RI "const \fB_XOR_MI_CRONTYPE_SCHEDULER\fP 'Windows Scheduled Task'"
.br
.ti -1c
.RI "const \fB_XOR_MI_CRONINTERVAL\fP 'Cron Interval'"
.br
.ti -1c
.RI "const \fB_XOR_MI_CRONINTERVAL_DESC\fP 'This is the interval in seconds between each cron'"
.br
.ti -1c
.RI "const \fB_XOR_ADMENU4\fP 'Dashboard'"
.br
.ti -1c
.RI "const \fB_XOR_ADMENU5\fP 'About Xortify'"
.br
.ti -1c
.RI "const \fB_XOR_MI_FAULT_DELAY\fP 'Number of second to delay function on fault!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_FAULT_DELAY_DESC\fP 'If a fault occurs in the preloader, xortify will delay this function before calling it again this many seconds (Default 10 minutes)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_CURL_TIMOUT\fP 'Total amount of seconds a \fBCURL\fP Waits for a Response'"
.br
.ti -1c
.RI "const \fB_XOR_MI_CURL_TIMOUT_DESC\fP 'This is the total amount of seconds a \fBCURL\fP waits for a response after resolving the DNS\&.'"
.br
.ti -1c
.RI "const \fB_XOR_MI_CURL_CONNECTTIMOUT\fP 'Total amount of seconds a \fBCURL\fP Waits for DNS to resolve'"
.br
.ti -1c
.RI "const \fB_XOR_MI_CURL_CONNECTTIMOUT_DESC\fP 'This is the total amount of seconds a \fBCURL\fP waits for a DNS Lookup to resolve\&.'"
.br
.ti -1c
.RI "const \fB_XOR_MI_XOOPS_GOOGLE_ANALYTICS_ACCOUNTID_FAILEDTOPASS\fP 'UA-27709249-1'"
.br
.ti -1c
.RI "const \fB_XOR_MI_XOOPS_GOOGLE_ANALYTICS_ACCOUNTID_USERPASSED\fP 'UA-27726722-1'"
.br
.ti -1c
.RI "const \fB_XOR_MI_CLIENT_GOOGLE_ANALYTICS_ACCOUNTID_FAILEDTOPASS\fP ''"
.br
.ti -1c
.RI "const \fB_XOR_MI_CLIENT_GOOGLE_ANALYTICS_ACCOUNTID_USERPASSED\fP ''"
.br
.ti -1c
.RI "const \fB_MI_XOR_NAME\fP 'Xortify'"
.br
.ti -1c
.RI "const \fB_MI_XOR_VERSION\fP '4\&.10'"
.br
.ti -1c
.RI "const \fB_MI_XOR_MODE_CLIENT\fP 'Client'"
.br
.ti -1c
.RI "const \fB_MI_XOR_MODE_SERVER\fP 'Server'"
.br
.ti -1c
.RI "const \fB_MI_XOR_USER_AGENT\fP '%s/%s %s Sector Network Security (%s)'"
.br
.ti -1c
.RI "const \fB_MI_XOR_RUNTIME\fP 'PHP ' \&. PHP_VERSION\&. ' ['\&.PHP_VERSION_ID \&. '], XOOPS '\&.XOOPS_VERSION"
.br
.ti -1c
.RI "const \fB_XOR_MI_URIREST\fP '\fBREST\fP API Cloud Base URL'"
.br
.ti -1c
.RI "const \fB_XOR_MI_URIREST_DESC\fP 'This is the URL for cURL or wGET for \fBREST\fP API Communication <i>(With Trailing Slash)</i>'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROTOCOL_CURLSERIAL\fP 'cURL Serilisation Protocol (\fBREST\fP)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROTOCOL_WGETSERIAL\fP 'wGET Serilisation Protocol (\fBREST\fP)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROTOCOL_CURLXML\fP 'cURL \fBXML\fP Exchange Protocol (\fBREST\fP)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROTOCOL_WGETXML\fP 'wGET \fBXML\fP Exchange Protocol (\fBREST\fP)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROTOCOL_LEGACY_CURLSERIAL\fP 'cURL Serilisation Protocol (Legacy)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROTOCOL_LEGACY_WGETSERIAL\fP 'wGET Serilisation Protocol (Legacy)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROTOCOL_LEGACY_CURLXML\fP 'cURL \fBXML\fP Exchange Protocol (Legacy)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROTOCOL_LEGACY_WGETXML\fP 'wGET \fBXML\fP Exchange Protocol (Legacy)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROTOCOL_LEGACY_CURL\fP '\fBCURL\fP Protocol (Legacy)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROTOCOL_LEGACY_JSON\fP '\fBJSON\fP Protocol (Legacy)'"
.br
.ti -1c
.RI "const \fB_MI_XOR_NOT_MODE_CLIENT\fP 'This part of the ' \&. \fB_MI_XOR_NAME\fP \&. ' Version ' \&. \fB_MI_XOR_VERSION\fP \&. ' Script is only for executing in Client Mode! (ERROR: _XORTIFY_NOT_CLIENT)'"
.br
.ti -1c
.RI "const \fB_MI_XOR_NOT_MODE_SERVER\fP 'This part of the ' \&. \fB_MI_XOR_NAME\fP \&. ' Version ' \&. \fB_MI_XOR_VERSION\fP \&. ' Script is only for executing in Server Mode! (ERROR: _XORTIFY_NOT_SERVER)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_BOUNCE\fP 'Server Bounce Relay Delay'"
.br
.ti -1c
.RI "const \fB_XOR_MI_BOUNCE_DESC\fP 'This is the relay delay for the software when it is in Server Mode only! <i>(Does not apply to Client Edition!)</i>'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SERVERCACHE\fP 'Server List Cache Time'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SERVERCACHE_DESC\fP 'This is the amount of time an Server List and it\\'s information on it is cached!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_GOOGLE_ANALYTICS\fP 'Enable Collection of google analytics data for xortify\&.com?'"
.br
.ti -1c
.RI "const \fB_XOR_MI_GOOGLE_ANALYTICS_DESC\fP 'If you are using google analytics yourself you will want to disable this!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_XORTIFY_INSTANCE_KEY_WASNOTWRITTEN\fP 'For some reason I was unable to delete and replace /modules/xortify/include/instance\&.php please manually edit this file to make this copy of xortify unique!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_DISABLED\fP 'Disabled!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_USERSTOCHECK\fP 'Number of Users to Crawl at IP Cache Time?'"
.br
.ti -1c
.RI "const \fB_XOR_MI_USERSTOCHECK_DESC\fP 'This is the number of Users to Crawl at IP Cache Time; you can disable checking your User Base by selecting \\'Disabled!\\''"
.br
.ti -1c
.RI "const \fB_XOR_MI_ALLOWEDSPAMS\fP 'Spam attempts allowed before ban\&.'"
.br
.ti -1c
.RI "const \fB_XOR_MI_ALLOWEDSPAMS_DESC\fP 'This is the number of times a user is blocked about spam before they are banned!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_CHECKSPAMS\fP 'Groups checked for SPAM'"
.br
.ti -1c
.RI "const \fB_XOR_MI_CHECKSPAMS_DESC\fP 'This is the groups for user is blocked & checked for spam before they are banned at the number of attempts above!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_MINIMUMWORDS\fP 'Major Text Box Minimum number of allowed words\&.'"
.br
.ti -1c
.RI "const \fB_XOR_MI_MINIMUMWORDS_DESC\fP 'This is the number of words allowed for a major text box by the selected groups!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_MINIMUMWORDSGROUPS\fP 'Major Text Box Minimum number of allowed words\&.'"
.br
.ti -1c
.RI "const \fB_XOR_MI_MINIMUMWORDSGROUPS_DESC\fP 'This is the number of words allowed for a major text box by the selected groups!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_ALLOWEDADULT\fP 'Allow Adult Keywords and Key Phrases\&.'"
.br
.ti -1c
.RI "const \fB_XOR_MI_ALLOWEDADULT_DESC\fP 'This is the groups to enable adult keywords for any selected group!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_PROTOCOL_MINIMUMCLOUD\fP 'Mimised Use of Cloud (\fBREST\fP)'"
.br
.ti -1c
.RI "const \fB_XOR_MI_MC_REQUIRED\fP '&nbsp;<font style='color:red;'>(Required for <strong>'\&._XOR_MI_PROTOCOL_MINIMUMCLOUD\&.'</strong>)</font>'"
.br
.ti -1c
.RI "const \fB_XOR_MI_MC_SPAMC\fP 'Command for SpamAssassin\\'s <i>SPAMC</i>'"
.br
.ti -1c
.RI "const \fB_XOR_MI_MC_SPAMC_DESC\fP 'Must include full path and executable filename for SpamAssassin\\'s SPAMC Executable!'\&.\fB_XOR_MI_MC_REQUIRED\fP"
.br
.ti -1c
.RI "const \fB_XOR_MI_MC_SFS_API\fP 'Stop Forum Spam\\'s API URI'"
.br
.ti -1c
.RI "const \fB_XOR_MI_MC_SFS_API_DESC\fP 'Full URI for <a href='http://stopforumspam\&.com'>Stop Forum Spams</a> API!'\&.\fB_XOR_MI_MC_REQUIRED\fP"
.br
.ti -1c
.RI "const \fB_XOR_MI_MC_SFS_KEY\fP 'Stop Forum\\'s Spam API Key\&.'"
.br
.ti -1c
.RI "const \fB_XOR_MI_MC_SFS_KEY_DESC\fP 'Full API KEy for <a href='http://stopforumspam\&.com'>Stop Forum Spams</a> API!'\&.\fB_XOR_MI_MC_REQUIRED\fP"
.br
.ti -1c
.RI "const \fB_XOR_MI_MC_PHP_API\fP 'Project Honeypots End URI for BL API\&.'"
.br
.ti -1c
.RI "const \fB_XOR_MI_MC_PHP_API_DESC\fP 'Full Domain Extraction for BL API on <a href='http://projecthoneypot\&.org'>Project Honeypots</a>!'\&.\fB_XOR_MI_MC_REQUIRED\fP"
.br
.ti -1c
.RI "const \fB_XOR_MI_MC_PHP_KEY\fP 'Project Honeypots BL API Key\&.'"
.br
.ti -1c
.RI "const \fB_XOR_MI_MC_PHP_KEY_DESC\fP 'BL API Key on <a href='http://projecthoneypot\&.org'>Project Honeypots</a>!'\&.\fB_XOR_MI_MC_REQUIRED\fP"
.br
.ti -1c
.RI "const \fB_XOR_MI_SPOOF_COMMENT\fP 'Comments Sentry'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SPOOF_REGISTRATION\fP 'Registration Sentry'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SPOOF_THREAD\fP 'Thread Sentry'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SPOOF_COMMENT_DESC\fP 'Displays a fake comment now form for the purposes of capturing spam and banning the submitter!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SPOOF_REGISTRATION_DESC\fP 'Displays a fake registrationw form for the purposes of capturing spam and banning the submitter!'"
.br
.ti -1c
.RI "const \fB_XOR_MI_SPOOF_THREAD_DESC\fP 'Displays a fake thread form for the purposes of capturing spam and banning the submitter!'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const _MI_XOR_CREDITS 'GI-JOE (Protector), WISHCRAFT, Trabis'"

.SS "const _MI_XOR_DESC 'Xortify - Sector Network Security - Fortify your XOOPS'"

.SS "const _MI_XOR_MODE_CLIENT 'Client'"

.SS "const _MI_XOR_MODE_SERVER 'Server'"

.SS "const _MI_XOR_NAME 'Xortify'"

.SS "const _MI_XOR_NOT_MODE_CLIENT 'This part of the ' \&. \fB_MI_XOR_NAME\fP \&. ' Version ' \&. \fB_MI_XOR_VERSION\fP \&. ' Script is only for executing in Client Mode! (ERROR: _XORTIFY_NOT_CLIENT)'"

.SS "const _MI_XOR_NOT_MODE_SERVER 'This part of the ' \&. \fB_MI_XOR_NAME\fP \&. ' Version ' \&. \fB_MI_XOR_VERSION\fP \&. ' Script is only for executing in Server Mode! (ERROR: _XORTIFY_NOT_SERVER)'"

.SS "const _MI_XOR_RUNTIME 'PHP ' \&. PHP_VERSION\&. ' ['\&.PHP_VERSION_ID \&. '], XOOPS '\&.XOOPS_VERSION"

.SS "const _MI_XOR_USER_AGENT '%s/%s %s Sector Network Security (%s)'"

.SS "const _MI_XOR_VERSION '4\&.10'"

.SS "const _XOR_ADMENU1 'Ban List'"

.SS "const _XOR_ADMENU2 'Sign-up'"

.SS "const _XOR_ADMENU3 'Usage Logs'"

.SS "const _XOR_ADMENU4 'Dashboard'"

.SS "const _XOR_ADMENU5 'About Xortify'"

.SS "const _XOR_FRM_DISCLAIMER 'Xortify Disclaimer'"

.SS "const _XOR_FRM_DISCLAIMER_AGREE 'Agree to Xortify Disclaimer'"

.SS "const _XOR_FRM_EMAIL 'Your Email Address'"

.SS "const _XOR_FRM_NOSOAP_DISCLAIMER '<strong>There is no API Communication with Xortify\&.com check you have PHP \fBSOAP\fP installed as an extension and you have no firewalls preventing normal \fBSOAP\fP Protocol Communication\&. You will not be able to continue until this message has been replaced with the Xortify Disclaimer\&.<br/><br/>The Submit button below will appear when this is working, xortify is currently <strong>Offline</strong>'"

.SS "const _XOR_FRM_PASS 'Your Password'"

.SS "const _XOR_FRM_PUZZEL 'Solve Puzzel'"

.SS "const _XOR_FRM_REGISTER 'Register with Xortify\&.com'"

.SS "const _XOR_FRM_TIMEZONE 'Your Timezone'"

.SS "const _XOR_FRM_TITLE 'Sign-up to Xortify\&.com - Fortify your XOOPS'"

.SS "const _XOR_FRM_UNAME 'Your Xortify Username'"

.SS "const _XOR_FRM_URL 'Your Primary URL'"

.SS "const _XOR_FRM_VIEWEMAIL 'View Your Email'"

.SS "const _XOR_FRM_VPASS 'Validate Your Password'"

.SS "const _XOR_MI_ALLOWEDADULT 'Allow Adult Keywords and Key Phrases\&.'"

.SS "const _XOR_MI_ALLOWEDADULT_DESC 'This is the groups to enable adult keywords for any selected group!'"

.SS "const _XOR_MI_ALLOWEDSPAMS 'Spam attempts allowed before ban\&.'"

.SS "const _XOR_MI_ALLOWEDSPAMS_DESC 'This is the number of times a user is blocked about spam before they are banned!'"

.SS "const _XOR_MI_BOUNCE 'Server Bounce Relay Delay'"

.SS "const _XOR_MI_BOUNCE_DESC 'This is the relay delay for the software when it is in Server Mode only! <i>(Does not apply to Client Edition!)</i>'"

.SS "const _XOR_MI_CHECKSPAMS 'Groups checked for SPAM'"

.SS "const _XOR_MI_CHECKSPAMS_DESC 'This is the groups for user is blocked & checked for spam before they are banned at the number of attempts above!'"

.SS "const _XOR_MI_CLIENT_GOOGLE_ANALYTICS_ACCOUNTID_FAILEDTOPASS ''"

.SS "const _XOR_MI_CLIENT_GOOGLE_ANALYTICS_ACCOUNTID_USERPASSED ''"

.SS "const _XOR_MI_CRONINTERVAL 'Cron Interval'"

.SS "const _XOR_MI_CRONINTERVAL_DESC 'This is the interval in seconds between each cron'"

.SS "const _XOR_MI_CRONTYPE 'Type of cron scheduling'"

.SS "const _XOR_MI_CRONTYPE_CRONTAB 'UNIX Cron Job'"

.SS "const _XOR_MI_CRONTYPE_DESC 'This is the type of scheduling system you are using for your cron job'"

.SS "const _XOR_MI_CRONTYPE_PRELOADER 'Preloader'"

.SS "const _XOR_MI_CRONTYPE_SCHEDULER 'Windows Scheduled Task'"

.SS "const _XOR_MI_CURL_CONNECTTIMOUT 'Total amount of seconds a \fBCURL\fP Waits for DNS to resolve'"

.SS "const _XOR_MI_CURL_CONNECTTIMOUT_DESC 'This is the total amount of seconds a \fBCURL\fP waits for a DNS Lookup to resolve\&.'"

.SS "const _XOR_MI_CURL_TIMOUT 'Total amount of seconds a \fBCURL\fP Waits for a Response'"

.SS "const _XOR_MI_CURL_TIMOUT_DESC 'This is the total amount of seconds a \fBCURL\fP waits for a response after resolving the DNS\&.'"

.SS "const _XOR_MI_DISABLED 'Disabled!'"

.SS "const _XOR_MI_FAULT_DELAY 'Number of second to delay function on fault!'"

.SS "const _XOR_MI_FAULT_DELAY_DESC 'If a fault occurs in the preloader, xortify will delay this function before calling it again this many seconds (Default 10 minutes)'"

.SS "const _XOR_MI_GOOGLE_ANALYTICS 'Enable Collection of google analytics data for xortify\&.com?'"

.SS "const _XOR_MI_GOOGLE_ANALYTICS_DESC 'If you are using google analytics yourself you will want to disable this!'"

.SS "const _XOR_MI_IPCACHE 'IP Cache Time'"

.SS "const _XOR_MI_IPCACHE_DESC 'This is the amount of time an IP Address and information on it is cached!'"

.SS "const _XOR_MI_LOG_BANNED 'Log Banned Action'"

.SS "const _XOR_MI_LOG_BANNED_DESC 'When Xortify Bans something on the cloud, then log it!'"

.SS "const _XOR_MI_LOG_BLOCKED 'Log Blocked Action'"

.SS "const _XOR_MI_LOG_BLOCKED_DESC 'When Xortify Blocks something as detected on the cloud, then log it!'"

.SS "const _XOR_MI_LOG_MONITORED 'Log Monitored Action'"

.SS "const _XOR_MI_LOG_MONITORED_DESC 'When Xortify Monitor\\'s something/someone as detected on the cloud, then log it!'"

.SS "const _XOR_MI_LOGDROPS 'Log Deletes Itself After'"

.SS "const _XOR_MI_LOGDROPS_DESC 'This is how long the log stays on your site for after a record reaches this age it is deleted!'"

.SS "const _XOR_MI_MC_PHP_API 'Project Honeypots End URI for BL API\&.'"

.SS "const _XOR_MI_MC_PHP_API_DESC 'Full Domain Extraction for BL API on <a href='http://projecthoneypot\&.org'>Project Honeypots</a>!'\&.\fB_XOR_MI_MC_REQUIRED\fP"

.SS "const _XOR_MI_MC_PHP_KEY 'Project Honeypots BL API Key\&.'"

.SS "const _XOR_MI_MC_PHP_KEY_DESC 'BL API Key on <a href='http://projecthoneypot\&.org'>Project Honeypots</a>!'\&.\fB_XOR_MI_MC_REQUIRED\fP"

.SS "const _XOR_MI_MC_REQUIRED '&nbsp;<font style='color:red;'>(Required for <strong>'\&._XOR_MI_PROTOCOL_MINIMUMCLOUD\&.'</strong>)</font>'"

.SS "const _XOR_MI_MC_SFS_API 'Stop Forum Spam\\'s API URI'"

.SS "const _XOR_MI_MC_SFS_API_DESC 'Full URI for <a href='http://stopforumspam\&.com'>Stop Forum Spams</a> API!'\&.\fB_XOR_MI_MC_REQUIRED\fP"

.SS "const _XOR_MI_MC_SFS_KEY 'Stop Forum\\'s Spam API Key\&.'"

.SS "const _XOR_MI_MC_SFS_KEY_DESC 'Full API KEy for <a href='http://stopforumspam\&.com'>Stop Forum Spams</a> API!'\&.\fB_XOR_MI_MC_REQUIRED\fP"

.SS "const _XOR_MI_MC_SPAMC 'Command for SpamAssassin\\'s <i>SPAMC</i>'"

.SS "const _XOR_MI_MC_SPAMC_DESC 'Must include full path and executable filename for SpamAssassin\\'s SPAMC Executable!'\&.\fB_XOR_MI_MC_REQUIRED\fP"

.SS "const _XOR_MI_MINIMUMWORDS 'Major Text Box Minimum number of allowed words\&.'"

.SS "const _XOR_MI_MINIMUMWORDS_DESC 'This is the number of words allowed for a major text box by the selected groups!'"

.SS "const _XOR_MI_MINIMUMWORDSGROUPS 'Major Text Box Minimum number of allowed words\&.'"

.SS "const _XOR_MI_MINIMUMWORDSGROUPS_DESC 'This is the number of words allowed for a major text box by the selected groups!'"

.SS "const _XOR_MI_PASSWORD 'Xortify Cloud Password'"

.SS "const _XOR_MI_PASSWORD_DESC 'You assign one of these by going to the menu <a href=''\&.XOOPS_URL\&.'/modules/xortify/admin/index\&.php?op=signup&fct=signup'>Sign-up</a>'"

.SS "const _XOR_MI_PHP_DAYS '%s day(s)'"

.SS "const _XOR_MI_PHP_NUMBEROFDAYS '<a href='http://www\&.projecthoneypot\&.org'>Project Honeypot</a> - Last Number of Days Seen'"

.SS "const _XOR_MI_PHP_NUMBEROFDAYS_DESC 'This is the number of days upto that the IP has been seen and flagged by project honeypot'"

.SS "const _XOR_MI_PHP_SCANMODE '<a href='http://www\&.projecthoneypot\&.org'>Project Honeypot</a> - What will be banned'"

.SS "const _XOR_MI_PHP_SCANMODE_DESC 'This list is in a hierachy which will ban from what you select and down in the list from severity\&.'"

.SS "const _XOR_MI_PHP_SCANMODE_HARVESTER 'Harvester IP'"

.SS "const _XOR_MI_PHP_SCANMODE_HARVESTERSPAMMER 'Harvester + Comment Spammer'"

.SS "const _XOR_MI_PHP_SCANMODE_SPAMMER 'Comment Spammer'"

.SS "const _XOR_MI_PHP_SCANMODE_SUSICIOUSHARVESTER 'Suspicious + Harvester IP'"

.SS "const _XOR_MI_PHP_SCANMODE_SUSPICIOUS 'Suspicious IP'"

.SS "const _XOR_MI_PHP_SCANMODE_SUSPICIOUSHARVESTERSPAMMER 'Suspicious + Harvester + Comment Spammer'"

.SS "const _XOR_MI_PHP_SCANMODE_SUSPICIOUSSPAMMER 'Suspicious + Comment Spammer'"

.SS "const _XOR_MI_PHP_SEVERITY '%s percent'"

.SS "const _XOR_MI_PHP_SEVERITYLEVEL '<a href='http://www\&.projecthoneypot\&.org'>Project Honeypot</a> - Severity Level of IP'"

.SS "const _XOR_MI_PHP_SEVERITYLEVEL_DESC 'This is the severity level on the honeypot that the IP has been seen and flagged by project honeypot'"

.SS "const _XOR_MI_PROTOCOL 'Cloud Communication Protocol'"

.SS "const _XOR_MI_PROTOCOL_CURL '\fBCURL\fP Protocol'"

.SS "const _XOR_MI_PROTOCOL_CURLSERIAL 'cURL Serilisation Protocol (\fBREST\fP)'"

.SS "const _XOR_MI_PROTOCOL_CURLXML 'cURL \fBXML\fP Exchange Protocol (\fBREST\fP)'"

.SS "const _XOR_MI_PROTOCOL_DESC 'This is the protocol that is used in the communication with the xortify cloud!'"

.SS "const _XOR_MI_PROTOCOL_JSON 'Open Access Protocol'"

.SS "const _XOR_MI_PROTOCOL_LEGACY_CURL '\fBCURL\fP Protocol (Legacy)'"

.SS "const _XOR_MI_PROTOCOL_LEGACY_CURLSERIAL 'cURL Serilisation Protocol (Legacy)'"

.SS "const _XOR_MI_PROTOCOL_LEGACY_CURLXML 'cURL \fBXML\fP Exchange Protocol (Legacy)'"

.SS "const _XOR_MI_PROTOCOL_LEGACY_JSON '\fBJSON\fP Protocol (Legacy)'"

.SS "const _XOR_MI_PROTOCOL_LEGACY_WGETSERIAL 'wGET Serilisation Protocol (Legacy)'"

.SS "const _XOR_MI_PROTOCOL_LEGACY_WGETXML 'wGET \fBXML\fP Exchange Protocol (Legacy)'"

.SS "const _XOR_MI_PROTOCOL_MINIMUMCLOUD 'Mimised Use of Cloud (\fBREST\fP)'"

.SS "const _XOR_MI_PROTOCOL_SOAP '\fBSOAP\fP Protocol'"

.SS "const _XOR_MI_PROTOCOL_WGETSERIAL 'wGET Serilisation Protocol (\fBREST\fP)'"

.SS "const _XOR_MI_PROTOCOL_WGETXML 'wGET \fBXML\fP Exchange Protocol (\fBREST\fP)'"

.SS "const _XOR_MI_PROVIDER_PROJECTHONEYPOT 'Project Honeypot'"

.SS "const _XOR_MI_PROVIDER_PROTECTOR 'Protector Module'"

.SS "const _XOR_MI_PROVIDER_SPIDERS 'Spiders Module'"

.SS "const _XOR_MI_PROVIDER_STOPFORUMSPAM 'Stop Forum Spam'"

.SS "const _XOR_MI_PROVIDER_XORTIFY 'Xortify Module'"

.SS "const _XOR_MI_PROVIDERS 'Provider Plug-ins'"

.SS "const _XOR_MI_PROVIDERS_DESC 'Provider\\'s that are supported by Xortify'"

.SS "const _XOR_MI_RECORDS 'Records to Retrieve!'"

.SS "const _XOR_MI_RECORDS_1200 '1200 Records'"

.SS "const _XOR_MI_RECORDS_12200 '12200 Records'"

.SS "const _XOR_MI_RECORDS_177600 '177600 Records'"

.SS "const _XOR_MI_RECORDS_180 '180 Records'"

.SS "const _XOR_MI_RECORDS_1800 '1800 Records'"

.SS "const _XOR_MI_RECORDS_24400 '24400 Records'"

.SS "const _XOR_MI_RECORDS_30 '30 Records'"

.SS "const _XOR_MI_RECORDS_300 '300 Records'"

.SS "const _XOR_MI_RECORDS_3600 '3600 Records'"

.SS "const _XOR_MI_RECORDS_48800 '48800 Records'"

.SS "const _XOR_MI_RECORDS_60 '60 Records'"

.SS "const _XOR_MI_RECORDS_600 '600 Records'"

.SS "const _XOR_MI_RECORDS_DESC 'Number of total records to retrieve!'"

.SS "const _XOR_MI_SECONDS 'Seconds to base Cache List on!'"

.SS "const _XOR_MI_SECONDS_1200 '20 minutes'"

.SS "const _XOR_MI_SECONDS_1209600 '1 Fortnight'"

.SS "const _XOR_MI_SECONDS_14400 '3 Hours'"

.SS "const _XOR_MI_SECONDS_14515200 '6 Months'"

.SS "const _XOR_MI_SECONDS_180 '3 Minutes'"

.SS "const _XOR_MI_SECONDS_1800 '30 minutes'"

.SS "const _XOR_MI_SECONDS_2419200 '1 Month'"

.SS "const _XOR_MI_SECONDS_28800 '4 Hours'"

.SS "const _XOR_MI_SECONDS_29030400 '1 Year'"

.SS "const _XOR_MI_SECONDS_30 '30 Seconds'"

.SS "const _XOR_MI_SECONDS_300 '5 Minutes'"

.SS "const _XOR_MI_SECONDS_3600 '1 Hour'"

.SS "const _XOR_MI_SECONDS_37600 '5 Hours'"

.SS "const _XOR_MI_SECONDS_43200 '12 Hours'"

.SS "const _XOR_MI_SECONDS_60 '1 Minute'"

.SS "const _XOR_MI_SECONDS_600 '10 minutes'"

.SS "const _XOR_MI_SECONDS_604800 '1 Week'"

.SS "const _XOR_MI_SECONDS_7200 '2 Hours'"

.SS "const _XOR_MI_SECONDS_7257600 '3 Months'"

.SS "const _XOR_MI_SECONDS_86400 '24 Hours'"

.SS "const _XOR_MI_SECONDS_DESC 'Period of time for ban list to be invocated!'"

.SS "const _XOR_MI_SERVERCACHE 'Server List Cache Time'"

.SS "const _XOR_MI_SERVERCACHE_DESC 'This is the amount of time an Server List and it\\'s information on it is cached!'"

.SS "const _XOR_MI_SFS_EMAIILFREQ 'Occured %s time(s)'"

.SS "const _XOR_MI_SFS_EMAILFREQUENCY '<a href='http://www\&.stopforumspam\&.com'>Stop Forum Spam</a> - Number of time email address has been reported'"

.SS "const _XOR_MI_SFS_EMAILFREQUENCY_DESC 'This is the number of time the email has been reported as spam and will ban the IP and details when it occurs at this level\&.'"

.SS "const _XOR_MI_SFS_EMAILLASTSEEN '<a href='http://www\&.stopforumspam\&.com'>Stop Forum Spam</a> - How long ago the email address was seen'"

.SS "const _XOR_MI_SFS_EMAILLASTSEEN_DESC 'This is the period of time allocated to wence the email was last seen, \fBif\fP it occured after this period it will not be banned!'"

.SS "const _XOR_MI_SFS_IPFREQ 'Occured %s time(s)'"

.SS "const _XOR_MI_SFS_IPFREQUENCY '<a href='http://www\&.stopforumspam\&.com'>Stop Forum Spam</a> - Number of time IP address has been reported'"

.SS "const _XOR_MI_SFS_IPFREQUENCY_DESC 'This is the number of time the IP Address has been reported as spam and will ban the IP and details when it occurs at this level\&.'"

.SS "const _XOR_MI_SFS_IPLASTSEEN '<a href='http://www\&.stopforumspam\&.com'>Stop Forum Spam</a> - How long ago the IP address was seen'"

.SS "const _XOR_MI_SFS_IPLASTSEEN_DESC 'This is the period of time allocated to wence the IP address was last seen, \fBif\fP it occured after this period it will not be banned!'"

.SS "const _XOR_MI_SFS_LASTSEEN_12MONTHS '1 Year'"

.SS "const _XOR_MI_SFS_LASTSEEN_1MONTH '1 Month'"

.SS "const _XOR_MI_SFS_LASTSEEN_1WEEK '1 Week'"

.SS "const _XOR_MI_SFS_LASTSEEN_24HOURS '24 Hours'"

.SS "const _XOR_MI_SFS_LASTSEEN_24MONTHS '2 Years'"

.SS "const _XOR_MI_SFS_LASTSEEN_2MONTHS '2 Months'"

.SS "const _XOR_MI_SFS_LASTSEEN_36MONTHS '3 Years'"

.SS "const _XOR_MI_SFS_LASTSEEN_3MONTHS '3 Months'"

.SS "const _XOR_MI_SFS_LASTSEEN_4MONTHS '4 Months'"

.SS "const _XOR_MI_SFS_LASTSEEN_5MONTHS '5 Months'"

.SS "const _XOR_MI_SFS_LASTSEEN_6MONTHS '6 Months'"

.SS "const _XOR_MI_SFS_LASTSEEN_FORTNIGHT 'A Fortnight'"

.SS "const _XOR_MI_SFS_UNAMEFREQ 'Occured %s time(s)'"

.SS "const _XOR_MI_SFS_UNAMEFREQUENCY '<a href='http://www\&.stopforumspam\&.com'>Stop Forum Spam</a> - Number of time username has been reported'"

.SS "const _XOR_MI_SFS_UNAMEFREQUENCY_DESC 'This is the number of time the username has been reported as spam and will ban the IP and details when it occurs at this level\&.'"

.SS "const _XOR_MI_SFS_UNAMELASTSEEN '<a href='http://www\&.stopforumspam\&.com'>Stop Forum Spam</a> - How long ago the username was seen'"

.SS "const _XOR_MI_SFS_UNAMELASTSEEN_DESC 'This is the period of time allocated to wence the username was last seen, \fBif\fP it occured after this period it will not be banned!'"

.SS "const _XOR_MI_SPOOF_COMMENT 'Comments Sentry'"

.SS "const _XOR_MI_SPOOF_COMMENT_DESC 'Displays a fake comment now form for the purposes of capturing spam and banning the submitter!'"

.SS "const _XOR_MI_SPOOF_REGISTRATION 'Registration Sentry'"

.SS "const _XOR_MI_SPOOF_REGISTRATION_DESC 'Displays a fake registrationw form for the purposes of capturing spam and banning the submitter!'"

.SS "const _XOR_MI_SPOOF_THREAD 'Thread Sentry'"

.SS "const _XOR_MI_SPOOF_THREAD_DESC 'Displays a fake thread form for the purposes of capturing spam and banning the submitter!'"

.SS "const _XOR_MI_URICURL '\fBCURL\fP Cloud Base URL'"

.SS "const _XOR_MI_URICURL_DESC 'This is the URL for \fBCURL\fP \fBJSON\fP Communication (With Trailing Slash)'"

.SS "const _XOR_MI_URIJSON 'Open Access Cloud Base URL'"

.SS "const _XOR_MI_URIJSON_DESC 'This is the URL for wGET \fBJSON\fP (With Trailing Slash)'"

.SS "const _XOR_MI_URIREST '\fBREST\fP API Cloud Base URL'"

.SS "const _XOR_MI_URIREST_DESC 'This is the URL for cURL or wGET for \fBREST\fP API Communication <i>(With Trailing Slash)</i>'"

.SS "const _XOR_MI_URISERIAL 'Serilisation Cloud Base URL'"

.SS "const _XOR_MI_URISERIAL_DESC 'This is the URL for Serialisation Communication in cURL or wGET (With Trailing Slash)'"

.SS "const _XOR_MI_URISOAP '\fBSOAP\fP Cloud Base URL'"

.SS "const _XOR_MI_URISOAP_DESC 'This is the URL for \fBSOAP\fP Communication (With Trailing Slash)'"

.SS "const _XOR_MI_URIXML '\fBXML\fP Cloud Base URL'"

.SS "const _XOR_MI_URIXML_DESC 'This is the URL for cURL or wGET for \fBXML\fP Communication (With Trailing Slash)'"

.SS "const _XOR_MI_USERNAME 'Xortify Cloud Username'"

.SS "const _XOR_MI_USERNAME_DESC 'You can get one of these by going to the menu <a href=''\&.XOOPS_URL\&.'/modules/xortify/admin/index\&.php?op=signup&fct=signup'>Sign-up</a>'"

.SS "const _XOR_MI_USERSTOCHECK 'Number of Users to Crawl at IP Cache Time?'"

.SS "const _XOR_MI_USERSTOCHECK_DESC 'This is the number of Users to Crawl at IP Cache Time; you can disable checking your User Base by selecting \\'Disabled!\\''"

.SS "const _XOR_MI_XOOPS_GOOGLE_ANALYTICS_ACCOUNTID_FAILEDTOPASS 'UA-27709249-1'"

.SS "const _XOR_MI_XOOPS_GOOGLE_ANALYTICS_ACCOUNTID_USERPASSED 'UA-27726722-1'"

.SS "const _XOR_MI_XORTIFY_INSTANCE_KEY_WASNOTWRITTEN 'For some reason I was unable to delete and replace /modules/xortify/include/instance\&.php please manually edit this file to make this copy of xortify unique!'"

.SS "const _XOR_USERCREATED_PLEASEACTIVATE 'Check Your Email for Activation Email, Click on the activation link to activate module!'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
