.TH "E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/include/post.loader.mainfile.php" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/include/post.loader.mainfile.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$check\fP = new \fBProviders\fP('postcheck')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$check = new \fBProviders\fP('postcheck')"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
