.TH "E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/protector/include/precheck.inc.php" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/protector/include/precheck.inc.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBprotector\fP"
.br
.in -1c
.SS "Constant Groups"

.in +1c
.ti -1c
.RI "\fBprotector\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBPROTECTOR_PRECHECK_INCLUDED\fP 1"
.br
.ti -1c
.RI "const \fBPROTECTOR_VERSION\fP file_get_contents(dirname(__FILE__) \&. '/version\&.txt')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const PROTECTOR_PRECHECK_INCLUDED 1"

.SS "const PROTECTOR_VERSION file_get_contents(dirname(__FILE__) \&. '/version\&.txt')"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
