.TH "protector" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
protector \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Protector
.PP
\fBCopyright:\fP
.RS 4
The XOOPS Project http://sourceforge.net/projects/xoops/  http://www.fsf.org/copyleft/gpl.html GNU public license
.RE
.PP
\fBAuthor:\fP
.RS 4
trabis lusopoemas@gmail.com 
.RE
.PP
\fBVersion:\fP
.RS 4
.RE
.PP
\fBId:\fP
.RS 4
\fBprecheck\&.inc\&.php\fP 8391 2011-12-02 22:32:34Z trabis 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
