.TH "Providers" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Providers \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinit\fP ($check)"
.br
.ti -1c
.RI "\fBProviders\fP ($check= 'precheck')"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$providers\fP = array()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "init ($check)"

.SS "\fBProviders\fP ($check = \fC'precheck'\fP)"

.SH "Field Documentation"
.PP 
.SS "$providers = array()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
