.TH "E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/class/rest_json.php" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/class/rest_json.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBREST_JSONXortifyExchange\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP(!function_exists('json_encode')) 
.br
\fBif\fP(!function_exists('json_decode')) \fB$GLOBALS\fP ['xoops'] = Xoops::getInstance()"
.br
.ti -1c
.RI "const \fBXOOPS_JSON_LIB\fP 'PHPJSON'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBif\fP (!function_exists('json_encode')) \fBif\fP (!function_exists('json_decode')) $GLOBALS['xoops'] = Xoops::getInstance()"

.SS "const XOOPS_JSON_LIB 'PHPJSON'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
