.TH "E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/cron/serverup.php" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/cron/serverup.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBxortify_getURLData\fP ($URI, $curl=false)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBSERVER1\fP (PHP- '\&.PHP_VERSION\&.') '\&.(defined('XOOPS_VERSION')?constant('XOOPS_VERSION')\&.' ' 'http://xortify\&.com/unban/?op=unban'"
.br
.ti -1c
.RI "const \fBSERVER2\fP 'http://xortify\&.xoops\&.org/unban/?op=unban'"
.br
.ti -1c
.RI "const \fBSERVER3\fP 'http://xortify\&.chronolabs\&.coop/unban/?op=unban'"
.br
.ti -1c
.RI "const \fBREPLACE\fP 'unban/?op=unban'"
.br
.ti -1c
.RI "const \fBSEARCHFOR\fP 'Solve Puzzel:'"
.br
.ti -1c
.RI "const \fBSOAP\fP 'soap/'"
.br
.ti -1c
.RI "const \fBCURL\fP 'curl/'"
.br
.ti -1c
.RI "const \fBJSON\fP 'json/'"
.br
.ti -1c
.RI "const \fBSERIAL\fP 'serial/'"
.br
.ti -1c
.RI "const \fBXML\fP 'xml/'"
.br
.ti -1c
.RI "const \fBREST\fP 'rest/'"
.br
.ti -1c
.RI "\fB$module_handler\fP = $GLOBALS['xoops']->getHandler('module')"
.br
.ti -1c
.RI "\fB$config_handler\fP = $GLOBALS['xoops']->getHandler('config')"
.br
.ti -1c
.RI "\fB$configitem_handler\fP = $GLOBALS['xoops']->getHandler('configitem')"
.br
.ti -1c
.RI "\fB$serverup\fP =false"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "xortify_getURLData ($URI, $curl = \fCfalse\fP)"

.SH "Variable Documentation"
.PP 
.SS "$config_handler = $GLOBALS['xoops']->getHandler('config')"

.SS "$configitem_handler = $GLOBALS['xoops']->getHandler('configitem')"

.SS "$module_handler = $GLOBALS['xoops']->getHandler('module')"

.SS "$serverup =false"

.SS "const CURL 'curl/'"

.SS "const JSON 'json/'"

.SS "const REPLACE 'unban/?op=unban'"

.SS "const REST 'rest/'"

.SS "const SEARCHFOR 'Solve Puzzel:'"

.SS "const SERIAL 'serial/'"

.SS "const SERVER1(PHP- '\&.PHP_VERSION\&.') '\&.(defined('XOOPS_VERSION')?constant('XOOPS_VERSION')\&.' ' 'http://xortify\&.com/unban/?op=unban'"

.SS "const SERVER2 'http://xortify\&.xoops\&.org/unban/?op=unban'"

.SS "const SERVER3 'http://xortify\&.chronolabs\&.coop/unban/?op=unban'"

.SS "const SOAP 'soap/'"

.SS "const XML 'xml/'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
