.TH "E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/blocks/spoof.php" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/blocks/spoof.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBb_xortify_spoof_comment\fP ($options)"
.br
.ti -1c
.RI "\fBb_xortify_spoof_registration\fP ($options)"
.br
.ti -1c
.RI "\fBb_xortify_spoof_thread\fP ($options)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$GLOBALS\fP ['xoops'] = Xoops::getInstance()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "b_xortify_spoof_comment ($options)"

.SS "b_xortify_spoof_registration ($options)"

.SS "b_xortify_spoof_thread ($options)"

.SH "Variable Documentation"
.PP 
.SS "$GLOBALS['xoops'] = Xoops::getInstance()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
