.TH "E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/class/wgetserialised.php" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/class/wgetserialised.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWGETSERIALISEDXortifyExchange\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$GLOBALS\fP ['xoops'] = Xoops::getInstance()"
.br
.ti -1c
.RI "const \fBXOOPS_SERIAL_LIB\fP 'PHPSERIAL'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$GLOBALS['xoops'] = Xoops::getInstance()"

.SS "const XOOPS_SERIAL_LIB 'PHPSERIAL'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
