.TH "XoopsFormTextArea" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XoopsFormTextArea \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits XoopsFormElement\&.
.PP
Inherited by \fBXoopsFormDhtmlTextArea\fP, and \fBXoopsFormEditor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($caption, $name, $value='', $rows=5, $cols=50, $placeholder= '')"
.br
.ti -1c
.RI "\fBgetRows\fP ()"
.br
.ti -1c
.RI "\fBgetCols\fP ()"
.br
.ti -1c
.RI "\fBgetPlaceholder\fP ()"
.br
.ti -1c
.RI "\fBrender\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A textarea 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ($caption, $name, $value = \fC''\fP, $rows = \fC5\fP, $cols = \fC50\fP, $placeholder = \fC''\fP)"
Constructor
.PP
\fBParameters:\fP
.RS 4
\fI$caption\fP caption 
.br
\fI$name\fP name 
.br
\fI$value\fP initial content 
.br
\fI$rows\fP number of rows 
.br
\fI$cols\fP number of columns 
.br
\fI$placeholder\fP placeholder for this element\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "getCols ()"
Get number of columns
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.SS "getPlaceholder ()"
Get placeholder for this element
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.SS "getRows ()"
get number of rows
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.SS "render ()"
prepare HTML for output
.PP
\fBReturns:\fP
.RS 4
string HTML 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
