.TH "E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/xoops_version.php" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/== SVN ==/Xortify/releases/XOOPS 2.6/4.11/htdocs/modules/xortify/xoops_version.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP(!defined('XOOPS_ROOT_PATH')) 
.br
\fBif\fP(!defined('_MI_XOR_MODE')) 
.br
define('_MI_XOR_MODE' \fB_MI_XOR_MODE_CLIENT\fP"
.br
.ti -1c
.RI "\fB$modversion\fP ['dirname'] = basename(dirname(__FILE__))"
.br
.ti -1c
.RI "\fB$modversion\fP ['name'] = \fB_MI_XOR_NAME\fP \&. ' (' \&. _MI_XOR_MODE \&. ')'"
.br
.ti -1c
.RI "\fB$modversion\fP ['version'] = \fB_MI_XOR_VERSION\fP"
.br
.ti -1c
.RI "\fB$modversion\fP ['releasedate'] = 'Saturday: March 25, 2013'"
.br
.ti -1c
.RI "\fB$modversion\fP ['module_status'] = 'Stable'"
.br
.ti -1c
.RI "\fB$modversion\fP ['description'] = \fB_MI_XOR_DESC\fP \&. ' ( Mode: ' \&. _MI_XOR_MODE \&. ' )'"
.br
.ti -1c
.RI "\fB$modversion\fP ['credits'] = \fB_MI_XOR_CREDITS\fP"
.br
.ti -1c
.RI "\fB$modversion\fP ['author'] = 'Wishcraft (Simon Roberts - simon@labs\&.coop)'"
.br
.ti -1c
.RI "\fB$modversion\fP ['help'] = ''"
.br
.ti -1c
.RI "\fB$modversion\fP ['license'] = 'GPL 3\&.0'"
.br
.ti -1c
.RI "\fB$modversion\fP ['official'] = 1"
.br
.ti -1c
.RI "\fB$modversion\fP ['image'] = 'images/xortify_slogo\&.png'"
.br
.ti -1c
.RI "\fB$modversion\fP ['website'] = 'xortify\&.com'"
.br
.ti -1c
.RI "\fB$modversion\fP ['release_info'] = 'Stable 2013/03/25'"
.br
.ti -1c
.RI "\fB$modversion\fP ['release_file'] = XOOPS_URL\&.'/modules/xortify/docs/changelog\&.txt'"
.br
.ti -1c
.RI "\fB$modversion\fP ['release_date'] = '2013/03/25'"
.br
.ti -1c
.RI "\fB$modversion\fP ['module_website_url'] = 'www\&.simonaroberts\&.com/projects/xortify-xoops-client/'"
.br
.ti -1c
.RI "\fB$modversion\fP ['module_website_name'] = 'Chronolabs Co-op'"
.br
.ti -1c
.RI "\fB$modversion\fP ['min_php'] = '5\&.2'"
.br
.ti -1c
.RI "\fB$modversion\fP ['min_xoops'] = '2\&.6\&.0'"
.br
.ti -1c
.RI "\fB$modversion\fP ['min_db'] = array('mysql'=>'5\&.0\&.7', 'mysqli'=>'5\&.0\&.7')"
.br
.ti -1c
.RI "\fB$modversion\fP ['author_realname'] = 'Simon Antony Roberts'"
.br
.ti -1c
.RI "\fB$modversion\fP ['author_website_url'] = 'http://sourceforge\&.net/projects/xortify/'"
.br
.ti -1c
.RI "\fB$modversion\fP ['author_website_name'] = 'Chronolabs Australia'"
.br
.ti -1c
.RI "\fB$modversion\fP ['author_email'] = 'simon@labs\&.coop'"
.br
.ti -1c
.RI "\fB$modversion\fP ['demo_site_url'] = 'Chronolabs Australia'"
.br
.ti -1c
.RI "\fB$modversion\fP ['demo_site_name'] = ''"
.br
.ti -1c
.RI "\fB$modversion\fP ['support_site_url'] = 'http://www\&.chronolabs\&.coops/forums/viewforum\&.php?forum=30'"
.br
.ti -1c
.RI "\fB$modversion\fP ['support_site_name'] = 'Chronolabs'"
.br
.ti -1c
.RI "\fB$modversion\fP ['submit_bug'] = 'http://www\&.chronolabs\&.coops/forums/viewforum\&.php?forum=30'"
.br
.ti -1c
.RI "\fB$modversion\fP ['submit_feature'] = 'http://www\&.chronolabs\&.coops/forums/viewforum\&.php?forum=30'"
.br
.ti -1c
.RI "\fB$modversion\fP ['usenet_group'] = 'sci\&.chronolabs'"
.br
.ti -1c
.RI "\fB$modversion\fP ['maillist_announcements'] = ''"
.br
.ti -1c
.RI "\fB$modversion\fP ['maillist_bugs'] = ''"
.br
.ti -1c
.RI "\fB$modversion\fP ['maillist_features'] = ''"
.br
.ti -1c
.RI "\fB$modversion\fP ['warning'] = 'For XOOPS 2\&.6\&.0'"
.br
.ti -1c
.RI "\fB$modversion\fP ['plugin'] = 1"
.br
.ti -1c
.RI "\fB$modversion\fP ['plugin_module'][] = 'protector'"
.br
.ti -1c
.RI "\fB$modversion\fP ['sqlfile']['mysql'] = 'sql/mysql\&.sql'"
.br
.ti -1c
.RI "\fB$modversion\fP ['tables'][0] = 'xortify_log'"
.br
.ti -1c
.RI "\fB$modversion\fP ['tables'][1] = 'xortify_servers'"
.br
.ti -1c
.RI "\fB$modversion\fP ['tables'][2] = 'xortify_emails'"
.br
.ti -1c
.RI "\fB$modversion\fP ['tables'][3] = 'xortify_emails_links'"
.br
.ti -1c
.RI "\fB$modversion\fP ['hasMain'] = 0"
.br
.ti -1c
.RI "\fB$modversion\fP ['onInstall'] = 'include/install\&.php'"
.br
.ti -1c
.RI "\fB$modversion\fP ['onUpdate'] = 'include/update\&.php'"
.br
.ti -1c
.RI "\fB$modversion\fP ['system_menu'] = 1"
.br
.ti -1c
.RI "\fB$modversion\fP ['hasAdmin'] = 1"
.br
.ti -1c
.RI "\fB$modversion\fP ['adminindex'] = 'admin/index\&.php?op=dashboard'"
.br
.ti -1c
.RI "\fB$modversion\fP ['adminmenu'] = 'admin/menu\&.php'"
.br
.ti -1c
.RI "\fB$i\fP = 0"
.br
.ti -1c
.RI "\fB$modversion\fP ['blocks'][$i]['file'] = 'spoof\&.php'"
.br
.ti -1c
.RI "\fB$modversion\fP ['blocks'][$i]['name'] = \fB_XOR_MI_SPOOF_COMMENT\fP"
.br
.ti -1c
.RI "\fB$modversion\fP ['blocks'][$i]['description'] = \fB_XOR_MI_SPOOF_COMMENT_DESC\fP"
.br
.ti -1c
.RI "\fB$modversion\fP ['blocks'][$i]['show_func'] = '\fBb_xortify_spoof_comment\fP'"
.br
.ti -1c
.RI "\fB$modversion\fP ['blocks'][$i]['template'] = 'xortify_block_spoof\&.html'"
.br
.ti -1c
.RI "\fB$modversion\fP ['config'][$i]['name'] = 'xortify_username'"
.br
.ti -1c
.RI "\fB$modversion\fP ['config'][$i]['title'] = '\fB_XOR_MI_USERNAME\fP'"
.br
.ti -1c
.RI "\fB$modversion\fP ['config'][$i]['description'] = '\fB_XOR_MI_USERNAME_DESC\fP'"
.br
.ti -1c
.RI "\fB$modversion\fP ['config'][$i]['formtype'] = 'text'"
.br
.ti -1c
.RI "\fB$modversion\fP ['config'][$i]['valuetype'] = 'text'"
.br
.ti -1c
.RI "\fB$modversion\fP ['config'][$i]['default'] = ''"
.br
.ti -1c
.RI "\fB$modversion\fP ['config'][$i]['options']"
.br
.ti -1c
.RI "\fB$options\fP = array()"
.br
.ti -1c
.RI "for($days=1;$days<=255;$days++) 
.br
$options[sprintf(\fB_XOR_MI_PHP_DAYS\fP \fB$days\fP = $days"
.br
.ti -1c
.RI "for($num=1;$num<=150;$num++) 
.br
$options[sprintf(\fB_XOR_MI_SFS_EMAIILFREQ\fP \fB$num\fP = $num"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "for ($days=1;$days<=255;$days++) $options[sprintf(\fB_XOR_MI_PHP_DAYS\fP $days = $days"

.SS "$i = 0"

.SS "$modversion['dirname'] = basename(dirname(__FILE__))"

.SS "$modversion['name'] = \fB_MI_XOR_NAME\fP \&. ' (' \&. _MI_XOR_MODE \&. ')'"

.SS "$modversion['version'] = \fB_MI_XOR_VERSION\fP"

.SS "$modversion['releasedate'] = 'Saturday: March 25, 2013'"

.SS "$modversion['module_status'] = 'Stable'"

.SS "$modversion['description'] = \fB_MI_XOR_DESC\fP \&. ' ( Mode: ' \&. _MI_XOR_MODE \&. ' )'"

.SS "$modversion['credits'] = \fB_MI_XOR_CREDITS\fP"

.SS "$modversion['author'] = 'Wishcraft (Simon Roberts - simon@labs\&.coop)'"

.SS "$modversion['help'] = ''"

.SS "$modversion['license'] = 'GPL 3\&.0'"

.SS "$modversion['official'] = 1"

.SS "$modversion['image'] = 'images/xortify_slogo\&.png'"

.SS "$modversion['website'] = 'xortify\&.com'"

.SS "$modversion['release_info'] = 'Stable 2013/03/25'"

.SS "$modversion['release_file'] = XOOPS_URL\&.'/modules/xortify/docs/changelog\&.txt'"

.SS "$modversion['release_date'] = '2013/03/25'"

.SS "$modversion['module_website_url'] = 'www\&.simonaroberts\&.com/projects/xortify-xoops-client/'"

.SS "$modversion['module_website_name'] = 'Chronolabs Co-op'"

.SS "$modversion['min_php'] = '5\&.2'"

.SS "$modversion['min_xoops'] = '2\&.6\&.0'"

.SS "$modversion['min_db'] = array('mysql'=>'5\&.0\&.7', 'mysqli'=>'5\&.0\&.7')"

.SS "$modversion['author_realname'] = 'Simon Antony Roberts'"

.SS "$modversion['author_website_url'] = 'http://sourceforge\&.net/projects/xortify/'"

.SS "$modversion['author_website_name'] = 'Chronolabs Australia'"

.SS "$modversion['author_email'] = 'simon@labs\&.coop'"

.SS "$modversion['demo_site_url'] = 'Chronolabs Australia'"

.SS "$modversion['demo_site_name'] = ''"

.SS "$modversion['support_site_url'] = 'http://www\&.chronolabs\&.coops/forums/viewforum\&.php?forum=30'"

.SS "$modversion['support_site_name'] = 'Chronolabs'"

.SS "$modversion['submit_bug'] = 'http://www\&.chronolabs\&.coops/forums/viewforum\&.php?forum=30'"

.SS "$modversion['submit_feature'] = 'http://www\&.chronolabs\&.coops/forums/viewforum\&.php?forum=30'"

.SS "$modversion['usenet_group'] = 'sci\&.chronolabs'"

.SS "$modversion['maillist_announcements'] = ''"

.SS "$modversion['maillist_bugs'] = ''"

.SS "$modversion['maillist_features'] = ''"

.SS "$modversion['warning'] = 'For XOOPS 2\&.6\&.0'"

.SS "$modversion['plugin'] = 1"

.SS "$modversion['plugin_module'][] = 'protector'"

.SS "$modversion['sqlfile']['mysql'] = 'sql/mysql\&.sql'"

.SS "$modversion['tables'][0] = 'xortify_log'"

.SS "$modversion['tables'][1] = 'xortify_servers'"

.SS "$modversion['tables'][2] = 'xortify_emails'"

.SS "$modversion['tables'][3] = 'xortify_emails_links'"

.SS "$modversion['hasMain'] = 0"

.SS "$modversion['onInstall'] = 'include/install\&.php'"

.SS "$modversion['onUpdate'] = 'include/update\&.php'"

.SS "$modversion['system_menu'] = 1"

.SS "$modversion['hasAdmin'] = 1"

.SS "$modversion['adminindex'] = 'admin/index\&.php?op=dashboard'"

.SS "$modversion['adminmenu'] = 'admin/menu\&.php'"

.SS "$modversion['blocks'][$i]['file'] = 'spoof\&.php'"

.SS "$modversion['blocks'][$i]['name'] = \fB_XOR_MI_SPOOF_COMMENT\fP"

.SS "$modversion['blocks'][$i]['description'] = \fB_XOR_MI_SPOOF_COMMENT_DESC\fP"

.SS "$modversion['blocks'][$i]['show_func'] = '\fBb_xortify_spoof_comment\fP'"

.SS "$modversion['blocks'][$i]['template'] = 'xortify_block_spoof\&.html'"

.SS "$modversion['config'][$i]['name'] = 'xortify_username'"

.SS "$modversion['config'][$i]['title'] = '\fB_XOR_MI_USERNAME\fP'"

.SS "$modversion['config'][$i]['description'] = '\fB_XOR_MI_USERNAME_DESC\fP'"

.SS "$modversion['config'][$i]['formtype'] = 'text'"

.SS "$modversion['config'][$i]['valuetype'] = 'text'"

.SS "$modversion['config'][$i]['default'] = ''"

.SS "$modversion['config'][$i]['options']"
\fBInitial value:\fP
.PP
.nf
= array(_XOR_MI_SECONDS_37600 => 37600, _XOR_MI_SECONDS_28800 => 28800, _XOR_MI_SECONDS_14400 => 14400, _XOR_MI_SECONDS_7200 => 7200,
                                            _XOR_MI_SECONDS_3600 => 3600, _XOR_MI_SECONDS_1800 => 1800, _XOR_MI_SECONDS_1200 => 1200, _XOR_MI_SECONDS_600 => 600,
                                            _XOR_MI_SECONDS_300 => 300, _XOR_MI_SECONDS_180 => 180, _XOR_MI_SECONDS_60 => 60, _XOR_MI_SECONDS_30 => 30)
.fi
.SS "for ($num=1;$num<=150;$num++) $options[sprintf(\fB_XOR_MI_SFS_IPFREQ\fP $num = $num"

.SS "$options = array()"

.SS "\fBif\fP (!defined('XOOPS_ROOT_PATH')) \fBif\fP (!defined('_MI_XOR_MODE')) define('_MI_XOR_MODE' _MI_XOR_MODE_CLIENT"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
