.TH "XortifyLog" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XortifyLog \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits XoopsObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXortifyLog\fP ()"
.br
.ti -1c
.RI "\fBtoArray\fP ()"
.br
.ti -1c
.RI "\fBrunPrePlugin\fP ($default=true)"
.br
.ti -1c
.RI "\fBrunPostPlugin\fP ($lid)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "runPostPlugin ($lid)"

.SS "runPrePlugin ($default = \fCtrue\fP)"

.SS "toArray ()"

.SS "\fBXortifyLog\fP ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
