.TH "xortify" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xortify \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Class for Blue Room Xortify Email 
.PP
\fBAuthor:\fP
.RS 4
Simon Roberts simon@labs.coop
.RE
.PP
XOOPS Xortify Email handler class\&. This class is responsible for providing data access mechanisms to the data source of XOOPS user class objects\&.
.PP
\fBAuthor:\fP
.RS 4
Simon Roberts simon@chronolabs.coop
.RE
.PP
Class for Blue Room Xortify Emails Linking 
.PP
\fBAuthor:\fP
.RS 4
Simon Roberts simon@labs.coop
.RE
.PP
XOOPS Xortify Emails Linking handler class\&. This class is responsible for providing data access mechanisms to the data source of XOOPS user class objects\&.
.PP
\fBAuthor:\fP
.RS 4
Simon Roberts simon@chronolabs.coop 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
