.TH "XortifyCorePreload" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XortifyCorePreload \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits XoopsPreloadItem\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBinit\fP ()"
.br
.ti -1c
.RI "static \fBeventCoreIncludeAuthSuccess\fP ($args)"
.br
.ti -1c
.RI "static \fBeventCoreIncludeCommonEnd\fP ($args)"
.br
.ti -1c
.RI "static \fBeventCoreHeaderCacheEnd\fP ($args)"
.br
.ti -1c
.RI "static \fBeventCoreHeaderAddmeta\fP ($args)"
.br
.ti -1c
.RI "static \fBhasAPIUserPass\fP ()"
.br
.ti -1c
.RI "static \fBgetFileListAsArray\fP ($dirname, $prefix='xortify')"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static eventCoreHeaderAddmeta ($args)\fC [static]\fP"

.SS "static eventCoreHeaderCacheEnd ($args)\fC [static]\fP"

.SS "static eventCoreIncludeAuthSuccess ($args)\fC [static]\fP"

.SS "static eventCoreIncludeCommonEnd ($args)\fC [static]\fP"

.SS "static getFileListAsArray ($dirname, $prefix = \fC'xortify'\fP)\fC [static]\fP"

.SS "static hasAPIUserPass ()\fC [static]\fP"

.SS "static init ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
