.TH "XortifySfsPreload" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XortifySfsPreload \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits XoopsPreloadItem\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeventApiServerEnd\fP ($args)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "eventApiServerEnd ($args)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
