.TH "XortifyPluginStopforumspam_com" 3 "Fri Jul 26 2013" "Version 4.11" "Xortify Client for XOOPS 2.6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XortifyPluginStopforumspam_com \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBannedPreHook\fP ($default, \fBXortifyLog\fP $log)"
.br
.ti -1c
.RI "\fBBlockedPreHook\fP ($default, \fBXortifyLog\fP $log)"
.br
.ti -1c
.RI "\fBMonitoredPreHook\fP ($default, \fBXortifyLog\fP $log)"
.br
.ti -1c
.RI "\fBBannedPostHook\fP (\fBXortifyLog\fP $log, $lid)"
.br
.ti -1c
.RI "\fBBlockedPostHook\fP (\fBXortifyLog\fP $log, $lid)"
.br
.ti -1c
.RI "\fBMonitoredPostHook\fP (\fBXortifyLog\fP $log, $lid)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "BannedPostHook (\fBXortifyLog\fP$log, $lid)"

.SS "BannedPreHook ($default, \fBXortifyLog\fP$log)"

.SS "BlockedPostHook (\fBXortifyLog\fP$log, $lid)"

.SS "BlockedPreHook ($default, \fBXortifyLog\fP$log)"

.SS "MonitoredPostHook (\fBXortifyLog\fP$log, $lid)"

.SS "MonitoredPreHook ($default, \fBXortifyLog\fP$log)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Client for XOOPS 2\&.6 from the source code\&.
