.TH "Q:/@websites@/coop/labs/dev2/config.php" 3 "Wed Jul 17 2013" "Version 4.11" "Xortify Honeypot PHP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Q:/@websites@/coop/labs/dev2/config.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fB_RUN_XORTIFY_URL\fP 'http://yoursite\&.com'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_USERNAME\fP 'testuser'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_PASSWORD\fP 'password'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_MYIPv4_ADDRESS\fP '127\&.0\&.0\&.1'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_MYIPv6_ADDRESS\fP '1270::assd:dde:ee:e\&.0:1'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_PROVIDERS\fP 'projecthoneypot\&.org|stopforumspam\&.com|xortify'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_CURL_CONNECTIONTIMEOUT\fP 45"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_CURL_TIMEOUT\fP 45"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_API_CURL\fP 'https://xortify\&.com/curl/'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_API_JSON\fP 'https://xortify\&.com/json/'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_API_XML\fP 'https://xortify\&.com/xml/'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_API_SOAP\fP 'https://xortify\&.com/soap/'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_API_SERIAL\fP 'https://xortify\&.com/serial/'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_API_REST\fP 'https://xortify\&.com/rest/'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_PROTOCOL\fP 'rest_curlserialised'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_ROOT_PATH\fP dirname(__FILE__)"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_VAR_PATH\fP dirname(__FILE__)"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_VERSION\fP '4\&.11'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_MINIUWORDS\fP 15"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_IPCACHE\fP 3600*18"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_FAULTDELAY\fP 750"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_PROJECTHONEYPOT_OCTETA\fP 92"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_PROJECTHONEYPOT_OCTETB\fP 15"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_PROJECTHONEYPOT_OCTETC\fP 2"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_SFS_IPFREQUENCY\fP 2"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_SFS_UNAMEFREQUENCY\fP 2"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_SFS_EMAILFREQUENCY\fP 2"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_SFS_IP_LASTSEEN\fP (60*60*24*7*4*3)"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_SFS_UNAME_LASTSEEN\fP (60*60*24*7*4*3)"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_SFS_EMAIL_LASTSEEN\fP (60*60*24*7*4*3)"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_SPAMS_ALLOWED\fP 10"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_SPAMS_ALLOWADULT\fP false"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const _RUN_XORTIFY_API_CURL 'https://xortify\&.com/curl/'"

.SS "const _RUN_XORTIFY_API_JSON 'https://xortify\&.com/json/'"

.SS "const _RUN_XORTIFY_API_REST 'https://xortify\&.com/rest/'"

.SS "const _RUN_XORTIFY_API_SERIAL 'https://xortify\&.com/serial/'"

.SS "const _RUN_XORTIFY_API_SOAP 'https://xortify\&.com/soap/'"

.SS "const _RUN_XORTIFY_API_XML 'https://xortify\&.com/xml/'"

.SS "const _RUN_XORTIFY_CURL_CONNECTIONTIMEOUT 45"

.SS "const _RUN_XORTIFY_CURL_TIMEOUT 45"

.SS "const _RUN_XORTIFY_FAULTDELAY 750"

.SS "const _RUN_XORTIFY_IPCACHE 3600*18"

.SS "const _RUN_XORTIFY_MINIUWORDS 15"

.SS "const _RUN_XORTIFY_MYIPv4_ADDRESS '127\&.0\&.0\&.1'"

.SS "const _RUN_XORTIFY_MYIPv6_ADDRESS '1270::assd:dde:ee:e\&.0:1'"

.SS "const _RUN_XORTIFY_PASSWORD 'password'"

.SS "const _RUN_XORTIFY_PROJECTHONEYPOT_OCTETA 92"

.SS "const _RUN_XORTIFY_PROJECTHONEYPOT_OCTETB 15"

.SS "const _RUN_XORTIFY_PROJECTHONEYPOT_OCTETC 2"

.SS "const _RUN_XORTIFY_PROTOCOL 'rest_curlserialised'"

.SS "const _RUN_XORTIFY_PROVIDERS 'projecthoneypot\&.org|stopforumspam\&.com|xortify'"

.SS "const _RUN_XORTIFY_ROOT_PATH dirname(__FILE__)"

.SS "const _RUN_XORTIFY_SFS_EMAIL_LASTSEEN (60*60*24*7*4*3)"

.SS "const _RUN_XORTIFY_SFS_EMAILFREQUENCY 2"

.SS "const _RUN_XORTIFY_SFS_IP_LASTSEEN (60*60*24*7*4*3)"

.SS "const _RUN_XORTIFY_SFS_IPFREQUENCY 2"

.SS "const _RUN_XORTIFY_SFS_UNAME_LASTSEEN (60*60*24*7*4*3)"

.SS "const _RUN_XORTIFY_SFS_UNAMEFREQUENCY 2"

.SS "const _RUN_XORTIFY_SPAMS_ALLOWADULT false"

.SS "const _RUN_XORTIFY_SPAMS_ALLOWED 10"

.SS "const _RUN_XORTIFY_URL 'http://yoursite\&.com'"

.SS "const _RUN_XORTIFY_USERNAME 'testuser'"

.SS "const _RUN_XORTIFY_VAR_PATH dirname(__FILE__)"

.SS "const _RUN_XORTIFY_VERSION '4\&.11'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot PHP Library from the source code\&.
