.TH "Q:/@websites@/coop/labs/dev2/include/post.header.addmeta.php" 3 "Wed Jul 17 2013" "Version 4.11" "Xortify Honeypot PHP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Q:/@websites@/coop/labs/dev2/include/post.header.addmeta.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$check\fP = new \fBProviders\fP('footerpostcheck')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$check = new \fBProviders\fP('footerpostcheck')"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot PHP Library from the source code\&.
