.TH "Q:/@websites@/coop/labs/dev2/class/auth/auth_soap.php" 3 "Wed Jul 17 2013" "Version 4.11" "Xortify Honeypot PHP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Q:/@websites@/coop/labs/dev2/class/auth/auth_soap.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBXortifyAuthSoap\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP(!defined('XORTIFY_API_LOCAL')) 
.br
define('XORTIFY_API_LOCAL' \fB_RUN_XORTIFY_API_SOAP\fP"
.br
.ti -1c
.RI "\fBif\fP(!file_exists(XOOPS_ROOT_PATH\&.'/class/soap/xoopssoap\&.php')) \fBelse\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBif\fP (!defined('XORTIFY_API_URI')) define('XORTIFY_API_URI' _RUN_XORTIFY_API_SOAP"

.SS "\fBif\fP (!file_exists(XOOPS_ROOT_PATH\&.'/class/soap/xoopssoap\&.php')) else"
\fBInitial value:\fP
.PP
.nf
{
    require_once (XOOPS_ROOT_PATH\&.'/class/soap/xoopssoap\&.php')
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot PHP Library from the source code\&.
