.TH "Q:/@websites@/coop/labs/dev2/include/constants.php" 3 "Wed Jul 17 2013" "Version 4.11" "Xortify Honeypot PHP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Q:/@websites@/coop/labs/dev2/include/constants.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fB_MI_RUN_XORTIFY_NAME\fP 'Xortify'"
.br
.ti -1c
.RI "const \fB_MI_RUN_XORTIFY_VERSION\fP '4\&.11'"
.br
.ti -1c
.RI "const \fB_MI_RUN_XORTIFY_USER_AGENT\fP '%s/%s %s Sector Network Security (%s)'"
.br
.ti -1c
.RI "const \fB_MI_RUN_XORTIFY_RUNTIME\fP 'PHP ' \&. PHP_VERSION\&. ' ['\&.PHP_VERSION_ID \&. '], XORTIFY '\&.\fB_MI_RUN_XORTIFY_VERSION\fP"
.br
.ti -1c
.RI "const \fB_RUN_RUN_XORTIFYTIFY_BAN_PHP_TYPE\fP 'Project Honey Pot Ban - Details:'"
.br
.ti -1c
.RI "const \fB_RUN_RUN_XORTIFYTIFY_BAN_PHP_OCTETA\fP 'Number of Days'"
.br
.ti -1c
.RI "const \fB_RUN_RUN_XORTIFYTIFY_BAN_PHP_OCTETB\fP 'Severity'"
.br
.ti -1c
.RI "const \fB_RUN_RUN_XORTIFYTIFY_BAN_PHP_OCTETC\fP 'Scan Mode'"
.br
.ti -1c
.RI "const \fB_RUN_RUN_XORTIFYTIFY_BAN_SPIDER_TYPE\fP 'Spider Block - $_POST Variables are:'"
.br
.ti -1c
.RI "const \fB_RUN_RUN_XORTIFYTIFY_BAN_SFS_TYPE\fP 'Stop Forum Spam Ban - Details:'"
.br
.ti -1c
.RI "const \fB_RUN_RUN_XORTIFYTIFY_BAN_SFS_EMAIL_FREQ\fP 'Email Frequency'"
.br
.ti -1c
.RI "const \fB_RUN_RUN_XORTIFYTIFY_BAN_SFS_EMAIL_LASTSEEN\fP 'Email Last Seen'"
.br
.ti -1c
.RI "const \fB_RUN_RUN_XORTIFYTIFY_BAN_SFS_USERNAME_FREQ\fP 'Usename Frequency'"
.br
.ti -1c
.RI "const \fB_RUN_RUN_XORTIFYTIFY_BAN_SFS_USERNAME_LASTSEEN\fP 'Username Last Seen'"
.br
.ti -1c
.RI "const \fB_RUN_RUN_XORTIFYTIFY_BAN_SFS_IP_FREQ\fP 'IP Frequency'"
.br
.ti -1c
.RI "const \fB_RUN_RUN_XORTIFYTIFY_BAN_SFS_IP_LASTSEEN\fP 'IP Last Seen'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_SPAM\fP 'SPAM'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_SPAM_CONTENTS\fP 'Spam Contents'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_SPAM_PAGETITLE\fP 'You have been blocked for trying to submit Spam!'"
.br
.ti -1c
.RI "const \fB_RUN_XORTIFY_SPAM_DESCRIPTION\fP '<p align='center'><img align='middle' src=''\&._RUN_XORTIFY_URL\&.'/images/accessdenied\&.png'></p><p align='center' style='font-size:18px'>You have been blocked from our site for submitting spam by Xortify, this is possibly done by one of our third parties! You will have %s attempts left then you will be banned!</p><div style='clear:both; height: 25px;'>&nbsp;</div><p align='center' style='font-size:14px'>IP Bans that is a ban that is based on the provider 'Xortify' are with your IP Can be removed by going to <a href='http://xortify\&.com/modules/unban/'>XORTIFY DOT COM</a><br/><br/>This ban is not permenant and will drop in 3 months!</p>'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const _MI_RUN_XORTIFY_NAME 'Xortify'"

.SS "const _MI_RUN_XORTIFY_RUNTIME 'PHP ' \&. PHP_VERSION\&. ' ['\&.PHP_VERSION_ID \&. '], XORTIFY '\&.\fB_MI_RUN_XORTIFY_VERSION\fP"

.SS "const _MI_RUN_XORTIFY_USER_AGENT '%s/%s %s Sector Network Security (%s)'"

.SS "const _MI_RUN_XORTIFY_VERSION '4\&.11'"

.SS "const _RUN_RUN_XORTIFYTIFY_BAN_PHP_OCTETA 'Number of Days'"

.SS "const _RUN_RUN_XORTIFYTIFY_BAN_PHP_OCTETB 'Severity'"

.SS "const _RUN_RUN_XORTIFYTIFY_BAN_PHP_OCTETC 'Scan Mode'"

.SS "const _RUN_RUN_XORTIFYTIFY_BAN_PHP_TYPE 'Project Honey Pot Ban - Details:'"

.SS "const _RUN_RUN_XORTIFYTIFY_BAN_SFS_EMAIL_FREQ 'Email Frequency'"

.SS "const _RUN_RUN_XORTIFYTIFY_BAN_SFS_EMAIL_LASTSEEN 'Email Last Seen'"

.SS "const _RUN_RUN_XORTIFYTIFY_BAN_SFS_IP_FREQ 'IP Frequency'"

.SS "const _RUN_RUN_XORTIFYTIFY_BAN_SFS_IP_LASTSEEN 'IP Last Seen'"

.SS "const _RUN_RUN_XORTIFYTIFY_BAN_SFS_TYPE 'Stop Forum Spam Ban - Details:'"

.SS "const _RUN_RUN_XORTIFYTIFY_BAN_SFS_USERNAME_FREQ 'Usename Frequency'"

.SS "const _RUN_RUN_XORTIFYTIFY_BAN_SFS_USERNAME_LASTSEEN 'Username Last Seen'"

.SS "const _RUN_RUN_XORTIFYTIFY_BAN_SPIDER_TYPE 'Spider Block - $_POST Variables are:'"

.SS "const _RUN_XORTIFY_SPAM 'SPAM'"

.SS "const _RUN_XORTIFY_SPAM_CONTENTS 'Spam Contents'"

.SS "const _RUN_XORTIFY_SPAM_DESCRIPTION '<p align='center'><img align='middle' src=''\&._RUN_XORTIFY_URL\&.'/images/accessdenied\&.png'></p><p align='center' style='font-size:18px'>You have been blocked from our site for submitting spam by Xortify, this is possibly done by one of our third parties! You will have %s attempts left then you will be banned!</p><div style='clear:both; height: 25px;'>&nbsp;</div><p align='center' style='font-size:14px'>IP Bans that is a ban that is based on the provider 'Xortify' are with your IP Can be removed by going to <a href='http://xortify\&.com/modules/unban/'>XORTIFY DOT COM</a><br/><br/>This ban is not permenant and will drop in 3 months!</p>'"

.SS "const _RUN_XORTIFY_SPAM_PAGETITLE 'You have been blocked for trying to submit Spam!'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot PHP Library from the source code\&.
