.TH "Q:/@websites@/coop/labs/dev2/class/curlxml.php" 3 "Wed Jul 17 2013" "Version 4.11" "Xortify Honeypot PHP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Q:/@websites@/coop/labs/dev2/class/curlxml.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCURLXMLXortifyExchange\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "foreach(get_loaded_extensions() 
.br
as $ext) \fBif\fP($nativecurl==true 
.br
&&$nativexml==true) \fBif\fP(!defined('XORTIFY_CURLXML_API')) 
.br
define('XORTIFY_CURLXML_API' \fB_RUN_XORTIFY_API_XML\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "foreach (get_loaded_extensions() as $ext) \fBif\fP ($nativecurl==true &&$nativexml==true) \fBif\fP (!defined('XORTIFY_CURLXML_API')) define('XORTIFY_CURLXML_API' _RUN_XORTIFY_API_XML"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot PHP Library from the source code\&.
