.TH "Q:/@websites@/coop/labs/dev2/class/rest_curlxml.php" 3 "Wed Jul 17 2013" "Version 4.11" "Xortify Honeypot PHP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Q:/@websites@/coop/labs/dev2/class/rest_curlxml.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBREST_CURLXMLXortifyExchange\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "foreach(get_loaded_extensions() 
.br
as $ext) \fBif\fP($nativecurl==true 
.br
&&$nativexml==true) \fBif\fP(!defined('XORTIFY_REST_API')) 
.br
define('XORTIFY_REST_API' \fB$_SESSION\fP ['xortify'][XORTIFY_INSTANCE_KEY][_MI_XOR_VERSION]['moduleConfig']['xortify_urirest']"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "foreach (get_loaded_extensions() as $ext) \fBif\fP ($nativecurl==true &&$nativexml==true) \fBif\fP (!defined('XORTIFY_REST_API')) define('XORTIFY_REST_API' $_SESSION['xortify'][XORTIFY_INSTANCE_KEY][_MI_XOR_VERSION]['moduleConfig']['xortify_urirest']"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot PHP Library from the source code\&.
