.TH "AccessTokenAuthentication" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AccessTokenAuthentication \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetTokens\fP ($grantType, $scopeUrl, $clientID, $clientSecret, $authUrl)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Microsoft v2\&.0 API Access Token Authentication Class Allows for Access Token Authentication string to be retreived
.PP
microsoft 
.PP
Definition at line 146 of file translator\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
