.TH "banFormRecaptcha" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
banFormRecaptcha \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits XoopsFormElement\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbanFormRecaptcha\fP ($caption= '', $public_key= '')"
.br
.ti -1c
.RI "\fBgetValue\fP ($encode=false)"
.br
.ti -1c
.RI "\fBrender\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file formrecaptcha\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbanFormRecaptcha\fP ($caption = \fC''\fP, $public_key = \fC''\fP)"
Constructor
.PP
\fBParameters:\fP
.RS 4
\fI$caption\fP Caption 
.br
\fI$value\fP Text 
.RE
.PP

.PP
Definition at line 51 of file formrecaptcha\&.php\&.
.SS "getValue ($encode = \fCfalse\fP)"
Get the 'value' attribute
.PP
\fBParameters:\fP
.RS 4
\fI$encode\fP To sanitizer the text? 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 64 of file formrecaptcha\&.php\&.
.SS "render ()"
Prepare HTML for output
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 74 of file formrecaptcha\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
