.TH "banMembers" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
banMembers \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits XoopsObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbanMembers\fP ($fid=null)"
.br
.ti -1c
.RI "\fBtoArray\fP ()"
.br
.ti -1c
.RI "\fBipaddy\fP ()"
.br
.ti -1c
.RI "\fBstory\fP ()"
.br
.ti -1c
.RI "\fBgetDomains\fP ()"
.br
.ti -1c
.RI "\fBgetEmailAddresses\fP ()"
.br
.ti -1c
.RI "\fBsendBanNotice\fP ()"
.br
.ti -1c
.RI "\fBlookupDomain\fP ($domain= '')"
.br
.ti -1c
.RI "\fBlookupIP\fP ()"
.br
.ti -1c
.RI "\fBvalidateEmail\fP ($email)"
.br
.ti -1c
.RI "\fBvalidateDomain\fP ($domain)"
.br
.ti -1c
.RI "\fBgetBaseDomain\fP ($url, $debug=0)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$_whois_url\fP = 'http://whois\&.labs\&.coop/v1/%s/html\&.api'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for Ban Profiler 
.PP
\fBAuthor:\fP
.RS 4
Simon Roberts (simon@labs.coop) 
.RE
.PP
\fBCopyright:\fP
.RS 4
copyright (c) 2010-2013 labs\&.coop 
.RE
.PP

.PP
Definition at line 33 of file members\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
