.TH "banMembersHandler" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
banMembersHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits XoopsPersistableObjectHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (&$db)"
.br
.ti -1c
.RI "\fBinsert\fP ($obj, $force=true)"
.br
.ti -1c
.RI "\fBget\fP ($id, $force=true)"
.br
.ti -1c
.RI "\fBgetObjects\fP ($criteria, $id_as_key=false, $as_object=true)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$_ipinfodb_key\fP = _MI_SERVER_IPINFODB_KEY"
.br
.in -1c
.SH "Detailed Description"
.PP 
XOOPS Ban Profiler handler class\&. This class is responsible for providing data access mechanisms to the data source of XOOPS user class objects\&.
.PP
\fBAuthor:\fP
.RS 4
Simon Roberts simon@labs.coop 
.RE
.PP

.PP
Definition at line 290 of file members\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
