.TH "bans" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bans \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Xortify Bans & Unbans Function
.PP
You may not change or alter any portion of this comment or credits of supporting developers from this source code or any supporting source code which is considered copyrighted (c) material of the original comment or credit authors\&. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&.
.PP
\fBCopyright:\fP
.RS 4
Chronolabs Coopertive (Australia) http://web.labs.coop  GNU GPL 2 (http://www.gnu.org/licenses/old-licenses/gpl-2.0.html)
.RE
.PP
ban 
.PP
\fBAuthor:\fP
.RS 4
Simon Roberts (wishcraft) - meshy@labs.coop
.RE
.PP
Class for Ban Profiler 
.PP
\fBAuthor:\fP
.RS 4
Simon Roberts (simon@labs.coop) 
.RE
.PP
\fBCopyright:\fP
.RS 4
copyright (c) 2010-2013 labs\&.coop
.RE
.PP
XOOPS Ban Profiler handler class\&. This class is responsible for providing data access mechanisms to the data source of XOOPS user class objects\&.
.PP
\fBAuthor:\fP
.RS 4
Simon Roberts simon@labs.coop 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
