.TH "class" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
class \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Xoops Form Class Elements
.PP
\fBCopyright:\fP
.RS 4
The XOOPS Project http://sourceforge.net/projects/xoops/  http://www.fsf.org/copyleft/gpl.html GNU public license 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
