.TH "deprecated" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBGlobal \fBnusoap_base::formatDump\fP ($str)\fP" 1c
.PP
.IP "\fBGlobal \fBsoap_server::add_to_map\fP ($methodname, $in, $out)\fP" 1c
.PP
.IP "\fBGlobal \fBsoap_transport_http::decodeChunked\fP ($buffer, $lb)\fP" 1c
.PP
.IP "\fBGlobal \fBsoapclient::getDefaultRpcParams\fP ()\fP" 1c
.PP
.IP "\fBGlobal \fBsoapclient::setDefaultRpcParams\fP ($rpcParams)\fP" 1c
.PP
.IP "\fBGlobal \fBwsdl::serializeParameters\fP ($operation, $direction, $parameters)\fP" 1c
.PP
.IP "\fBGlobal \fBXMLSchema::getPHPType\fP ($type, $ns)\fP" 1c
.PP
.IP "\fBGlobal \fBXMLSchema::serializeTypeDef\fP ($type)\fP" 1c
.PP
.IP "\fBGlobal \fBXMLSchema::typeToForm\fP ($name, $type)\fP" 1c
.PP
.PP

