.TH "E:/Packages/xortify server/htdocs/modules/xsoap/language/english Directory Reference" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Packages/xortify server/htdocs/modules/xsoap/language/english Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBadmin\&.php\fP"
.br
.ti -1c
.RI "file \fBmain\&.php\fP"
.br
.ti -1c
.RI "file \fBmodinfo\&.php\fP"
.br
.in -1c
