.TH "E:/Packages/xortify server/htdocs/modules/xrest/include Directory Reference" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Packages/xortify server/htdocs/modules/xrest/include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcommon\&.php\fP"
.br
.ti -1c
.RI "file \fBforms\&.xrest\&.php\fP"
.br
.ti -1c
.RI "file \fBfunctions\&.php\fP"
.br
.ti -1c
.RI "file \fBJSON\&.php\fP"
.br
.ti -1c
.RI "file \fBserver\&.php\fP"
.br
.in -1c
