.TH "E:/Packages/xortify server/htdocs/modules/xrest/class Directory Reference" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Packages/xortify server/htdocs/modules/xrest/class Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfields\&.php\fP"
.br
.ti -1c
.RI "file \fBplugins\&.php\fP"
.br
.ti -1c
.RI "file \fBtables\&.php\fP"
.br
.in -1c
