.TH "E:/Packages/xortify server/htdocs/modules/xrest Directory Reference" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Packages/xortify server/htdocs/modules/xrest Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBadmin\fP"
.br
.ti -1c
.RI "directory \fBclass\fP"
.br
.ti -1c
.RI "directory \fBinclude\fP"
.br
.ti -1c
.RI "directory \fBlanguage\fP"
.br
.ti -1c
.RI "directory \fBplugins\fP"
.br
.ti -1c
.RI "directory \fBpreloads\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBindex\&.php\fP"
.br
.ti -1c
.RI "file \fBxoops_version\&.php\fP"
.br
.in -1c
