.TH "E:/Packages/xortify server/htdocs/modules/xortify/providers Directory Reference" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Packages/xortify server/htdocs/modules/xortify/providers Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBprojecthoneypot\&.org\fP"
.br
.ti -1c
.RI "directory \fBprotector\fP"
.br
.ti -1c
.RI "directory \fBspiders\fP"
.br
.ti -1c
.RI "directory \fBstopforumspam\&.com\fP"
.br
.ti -1c
.RI "directory \fBxortify\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBproviders\&.php\fP"
.br
.in -1c
