.TH "E:/Packages/xortify server/htdocs/modules/xortify/class/auth Directory Reference" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Packages/xortify server/htdocs/modules/xortify/class/auth Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBauth\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_curl\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_curl_provisionning\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_curlserialised\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_curlserialised_provisionning\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_curlxml\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_curlxml_provisionning\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_json\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_json_provisionning\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_rest_curl\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_rest_curl_provisionning\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_rest_curlserialised\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_rest_curlserialised_provisionning\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_rest_curlxml\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_rest_curlxml_provisionning\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_rest_json\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_rest_json_provisionning\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_rest_wgetserialised\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_rest_wgetserialised_provisionning\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_rest_wgetxml\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_rest_wgetxml_provisionning\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_soap\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_soap_provisionning\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_wgetserialised\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_wgetserialised_provisionning\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_wgetxml\&.php\fP"
.br
.ti -1c
.RI "file \fBauth_wgetxml_provisionning\&.php\fP"
.br
.ti -1c
.RI "file \fBauthfactory\&.php\fP"
.br
.in -1c
