.TH "E:/Packages/xortify server/htdocs/cron Directory Reference" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Packages/xortify server/htdocs/cron Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcleaner\&.php\fP"
.br
.ti -1c
.RI "file \fBunbanner\&.php\fP"
.br
.in -1c
