.TH "E:/Packages/xortify server/htdocs/include Directory Reference" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Packages/xortify server/htdocs/include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcloud\fP"
.br
.ti -1c
.RI "directory \fBlibs\fP"
.br
.ti -1c
.RI "directory \fBxsd\fP"
.br
.in -1c
