.TH "E:/Packages/xortify server/htdocs/include/xsd/legacy Directory Reference" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Packages/xortify server/htdocs/include/xsd/legacy Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBban\&.php\fP"
.br
.ti -1c
.RI "file \fBban_diff\&.php\fP"
.br
.ti -1c
.RI "file \fBbanned\&.php\fP"
.br
.ti -1c
.RI "file \fBbans\&.php\fP"
.br
.ti -1c
.RI "file \fBcheckphpbans\&.php\fP"
.br
.ti -1c
.RI "file \fBchecksfsbans\&.php\fP"
.br
.ti -1c
.RI "file \fBcloud_users\&.php\fP"
.br
.ti -1c
.RI "file \fBcloud_users_count\&.php\fP"
.br
.ti -1c
.RI "file \fBcomments\&.php\fP"
.br
.ti -1c
.RI "file \fBlanguages\&.php\fP"
.br
.ti -1c
.RI "file \fBnewusers\&.php\fP"
.br
.ti -1c
.RI "file \fBrep_spider\&.php\fP"
.br
.ti -1c
.RI "file \fBrep_spiderstat\&.php\fP"
.br
.ti -1c
.RI "file \fBseolinks\&.php\fP"
.br
.ti -1c
.RI "file \fBserver\&.php\fP"
.br
.ti -1c
.RI "file \fBserver_create_user\&.php\fP"
.br
.ti -1c
.RI "file \fBservers\&.php\fP"
.br
.ti -1c
.RI "file \fBsfsban\&.php\fP"
.br
.ti -1c
.RI "file \fBspamcheck\&.php\fP"
.br
.ti -1c
.RI "file \fBspider\&.php\fP"
.br
.ti -1c
.RI "file \fBspiders\&.php\fP"
.br
.ti -1c
.RI "file \fBspiderstat\&.php\fP"
.br
.ti -1c
.RI "file \fBspoofcomment\&.php\fP"
.br
.ti -1c
.RI "file \fBspoofregistration\&.php\fP"
.br
.ti -1c
.RI "file \fBspoofthread\&.php\fP"
.br
.ti -1c
.RI "file \fBtraining\&.php\fP"
.br
.ti -1c
.RI "file \fBtweet\&.php\fP"
.br
.ti -1c
.RI "file \fBunbanned\&.php\fP"
.br
.ti -1c
.RI "file \fBunbans\&.php\fP"
.br
.ti -1c
.RI "file \fBxoops_authentication\&.php\fP"
.br
.ti -1c
.RI "file \fBxoops_check_activation\&.php\fP"
.br
.ti -1c
.RI "file \fBxoops_create_user\&.php\fP"
.br
.ti -1c
.RI "file \fBxoops_network_disclaimer\&.php\fP"
.br
.ti -1c
.RI "file \fBxoops_user_validate\&.php\fP"
.br
.in -1c
