.TH "E:/Packages/xortify server/htdocs/modules/xortify/language Directory Reference" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Packages/xortify server/htdocs/modules/xortify/language Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBenglish\fP"
.br
.in -1c
