.TH "FunctionsHandler" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FunctionsHandler \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($\fBwsdl\fP)"
.br
.ti -1c
.RI "\fBGetServerExtensions\fP ()"
.br
.ti -1c
.RI "\fBgetDirListAsArray\fP ($dirname)"
.br
.ti -1c
.RI "\fBgetFileListAsArray\fP ($dirname, $prefix='')"
.br
.ti -1c
.RI "\fB__construct\fP ($\fBwsdl\fP)"
.br
.ti -1c
.RI "\fBGetServerExtensions\fP ()"
.br
.ti -1c
.RI "\fBgetDirListAsArray\fP ($dirname)"
.br
.ti -1c
.RI "\fBgetFileListAsArray\fP ($dirname, $prefix='')"
.br
.ti -1c
.RI "\fB__construct\fP ($\fBwsdl\fP)"
.br
.ti -1c
.RI "\fBGetServerExtensions\fP ()"
.br
.ti -1c
.RI "\fBgetDirListAsArray\fP ($dirname)"
.br
.ti -1c
.RI "\fBgetFileListAsArray\fP ($dirname, $prefix='')"
.br
.ti -1c
.RI "\fB__construct\fP ($\fBwsdl\fP)"
.br
.ti -1c
.RI "\fBGetServerExtensions\fP ()"
.br
.ti -1c
.RI "\fBgetDirListAsArray\fP ($dirname)"
.br
.ti -1c
.RI "\fBgetFileListAsArray\fP ($dirname, $prefix='')"
.br
.ti -1c
.RI "\fB__construct\fP ($\fBwsdl\fP)"
.br
.ti -1c
.RI "\fBGetServerExtensions\fP ()"
.br
.ti -1c
.RI "\fBgetDirListAsArray\fP ($dirname)"
.br
.ti -1c
.RI "\fBgetFileListAsArray\fP ($dirname, $prefix='')"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$functions\fP =array()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file class\&.functions\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
