.TH "ip2location_lite" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ip2location_lite \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetKey\fP ($key)"
.br
.ti -1c
.RI "\fBgetError\fP ()"
.br
.ti -1c
.RI "\fBgetCountry\fP ($host)"
.br
.ti -1c
.RI "\fBgetCity\fP ($host)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$errors\fP = array()"
.br
.ti -1c
.RI "\fB$service\fP = 'api\&.ipinfodb\&.com'"
.br
.ti -1c
.RI "\fB$version\fP = 'v3'"
.br
.ti -1c
.RI "\fB$apiKey\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file ip2locationlite\&.class\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
