.TH "Providers" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Providers \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinit\fP ($check)"
.br
.ti -1c
.RI "\fB__construct\fP ($check= 'precheck')"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$providers\fP = array()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file providers\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "init ($check)"
Get xoops configs Requires functions and database loaded
.PP
User Sessions
.PP
Definition at line 45 of file providers\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
