.TH "ReCaptchaResponse" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReCaptchaResponse \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$is_valid\fP"
.br
.ti -1c
.RI "\fB$error\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBReCaptchaResponse\fP is returned from recaptcha_check_answer() 
.PP
Definition at line 137 of file recaptchalib\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
