.TH "REST_WGETXMLXortifyExchange" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REST_WGETXMLXortifyExchange \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWGETXMLXortifyExchange\fP ()"
.br
.ti -1c
.RI "\fBcheckForSpam\fP ($content)"
.br
.ti -1c
.RI "\fBgetServers\fP ()"
.br
.ti -1c
.RI "\fBsendBan\fP ($comment, $category_id=2, $ip=false)"
.br
.ti -1c
.RI "\fBcheckSFSBans\fP ($ipdata)"
.br
.ti -1c
.RI "\fBcheckPHPBans\fP ($ipdata)"
.br
.ti -1c
.RI "\fBgetBans\fP ()"
.br
.ti -1c
.RI "\fBretrieveBans\fP ()"
.br
.ti -1c
.RI "\fBcheckBanned\fP ($ipdata)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$xml_xoops_username\fP = ''"
.br
.ti -1c
.RI "\fB$xml_xoops_password\fP = ''"
.br
.ti -1c
.RI "\fB$refresh\fP = 600"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file rest_wgetxml\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
