.TH "Services_JSON" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Services_JSON \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Michal Migurski mike-json@teczno.com 
.PP
Matt Knapp <mdknapp[at]gmail[dot]com> 
.PP
Brett Stimmerman <brettstimmerman[at]gmail[dot]com> 
.RE
.PP
\fBCopyright:\fP
.RS 4
2005 Michal Migurski 
.RE
.PP
\fBVersion:\fP
.RS 4
CVS: 
.RE
.PP
\fBId:\fP
.RS 4
JSON\&.php,v 1\&.31 2006/06/28 05:54:17 migurski Exp 
.RE
.PP
http://www.opensource.org/licenses/bsd-license.php \fBhttp://pear\&.php\&.net/pepr/pepr-proposal-show\&.php?id=198\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
