.TH "SOAPSpidersExchange" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOAPSpidersExchange \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSOAPSpidersExchange\fP ()"
.br
.ti -1c
.RI "\fBsendSpider\fP ($spider)"
.br
.ti -1c
.RI "\fBsendStatistic\fP ($statistic)"
.br
.ti -1c
.RI "\fBgetSpiders\fP ()"
.br
.ti -1c
.RI "\fBgetSEOLinks\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$soap_client\fP"
.br
.ti -1c
.RI "\fB$soap_xoops_username\fP = ''"
.br
.ti -1c
.RI "\fB$soap_xoops_password\fP = ''"
.br
.ti -1c
.RI "\fB$refresh\fP = 600"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file soap\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
