.TH "SpidersSpidersHandler" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpidersSpidersHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits XoopsPersistableObjectHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (&$db)"
.br
.ti -1c
.RI "\fBbanDetails\fP ($details_url)"
.br
.ti -1c
.RI "\fBgetReverseNetaddyIPData\fP ($addr=false)"
.br
.ti -1c
.RI "\fBgetIPData\fP ($ip=false)"
.br
.ti -1c
.RI "\fBis_ipv6\fP ($ip='')"
.br
.ti -1c
.RI "\fBsafeAgent\fP ($useragent)"
.br
.ti -1c
.RI "\fBimport_insert\fP ($spider)"
.br
.ti -1c
.RI "\fBgetRobotHostandIP\fP ()"
.br
.ti -1c
.RI "\fBisSpiderHost\fP ($ip)"
.br
.ti -1c
.RI "\fBisSpiderAgent\fP ($useragent, $return_object=false)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file spiders\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
