.TH "SpidersStatistics" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpidersStatistics \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits XoopsObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpidersStatistics\fP ($fid=null)"
.br
.ti -1c
.RI "\fBgetStory\fP ()"
.br
.ti -1c
.RI "\fBxoopsTweetString\fP ($title, $doit=false, $wordlen=4)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file statistics\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
