.TH "unbanCategoriesHandler" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unbanCategoriesHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits XoopsPersistableObjectHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (&$db)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file categories\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
