.TH "xortify" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xortify \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
module  Sector Network Security Drone 
.PP
\fBAuthor:\fP
.RS 4
Simon Roberts WISHCRAFT simon@labs.coop 
.RE
.PP
\fBCopyright:\fP
.RS 4
copyright (c) 2010-2013 XOOPS\&.org  docs/End User Licence\&.pdf
.RE
.PP
Class for Blue Room Xortify Email 
.PP
\fBAuthor:\fP
.RS 4
Simon Roberts simon@xoops.org 
.RE
.PP
\fBCopyright:\fP
.RS 4
copyright (c) 2009-2003 XOOPS\&.org
.RE
.PP
XOOPS Xortify Email handler class\&. This class is responsible for providing data access mechanisms to the data source of XOOPS user class objects\&.
.PP
\fBAuthor:\fP
.RS 4
Simon Roberts simon@labs.coop
.RE
.PP
Class for Blue Room Xortify Emails Linking 
.PP
\fBAuthor:\fP
.RS 4
Simon Roberts simon@xoops.org 
.RE
.PP
\fBCopyright:\fP
.RS 4
copyright (c) 2009-2003 XOOPS\&.org
.RE
.PP
XOOPS Xortify Emails Linking handler class\&. This class is responsible for providing data access mechanisms to the data source of XOOPS user class objects\&.
.PP
\fBAuthor:\fP
.RS 4
Simon Roberts simon@labs.coop
.RE
.PP
module  Sector Nexoork Security Drone 
.PP
\fBAuthor:\fP
.RS 4
Simon Roberts WISHCRAFT simon@labs.coop 
.PP
Richardo Costa TRABIS 
.RE
.PP
\fBCopyright:\fP
.RS 4
copyright (c) 2010-2013 XOOPS\&.org  GPL 2\&.0 - see docs/LICENCE\&.txt 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
