.TH "XortifyAuthRest_Wgetxml" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XortifyAuthRest_Wgetxml \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBXortifyAuth\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXortifyAuthRest_Wgetxml\fP (&$dao)"
.br
.ti -1c
.RI "\fBauthenticate\fP ($uname, $pwd=null)"
.br
.ti -1c
.RI "\fBvalidate\fP ($uname, $email, $pass, $vpass)"
.br
.ti -1c
.RI "\fBreduce_string\fP ($str)"
.br
.ti -1c
.RI "\fBnetwork_disclaimer\fP ()"
.br
.ti -1c
.RI "\fBcreate_user\fP ($user_viewemail, $uname, $email, $url, $actkey, $pass, $timezone_offset, $user_mailok, $siteinfo)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$xml_xoops_username\fP = ''"
.br
.ti -1c
.RI "\fB$xml_xoops_password\fP = ''"
.br
.ti -1c
.RI "\fB$_dao\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file auth_rest_wgetxml\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "authenticate ($uname, $pwd = \fCnull\fP)"
Authenticate user again json directory (Bind)
.PP
\fBParameters:\fP
.RS 4
\fI$uname\fP Username 
.br
\fI$pwd\fP Password
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 60 of file auth_rest_wgetxml\&.php\&.
.SS "create_user ($user_viewemail, $uname, $email, $url, $actkey, $pass, $timezone_offset, $user_mailok, $siteinfo)"
create a user
.PP
\fBParameters:\fP
.RS 4
\fI$user_viewemail\fP 
.br
\fI$uname\fP 
.br
\fI$email\fP 
.br
\fI$url\fP 
.br
\fI$actkey\fP 
.br
\fI$pass\fP 
.br
\fI$timezone_offset\fP 
.br
\fI$user_mailok\fP 
.br
\fI$siteinfo\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 143 of file auth_rest_wgetxml\&.php\&.
.SS "network_disclaimer ()"
get the xoops site disclaimer via json
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 115 of file auth_rest_wgetxml\&.php\&.
.SS "validate ($uname, $email, $pass, $vpass)"
validate a user via json
.PP
\fBParameters:\fP
.RS 4
\fI$uname\fP 
.br
\fI$email\fP 
.br
\fI$pass\fP 
.br
\fI$vpass\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 79 of file auth_rest_wgetxml\&.php\&.
.SS "\fBXortifyAuthRest_Wgetxml\fP (&$dao)"
Authentication Service constructor 
.PP
Definition at line 47 of file auth_rest_wgetxml\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
