.TH "XortifyServers" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XortifyServers \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits XoopsObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXortifyServers\fP ($id=null)"
.br
.ti -1c
.RI "\fBtoArray\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file servers\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
