.TH "XortifyEmails" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XortifyEmails \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits XoopsObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXortifyEmails\fP ($id=null)"
.br
.ti -1c
.RI "\fBtoArray\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$_ip\fP = '127\&.0\&.0\&.1'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file emails\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
