.TH "XortifyAuthCurlxmlProvisionning" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XortifyAuthCurlxmlProvisionning \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "& \fBgetInstance\fP (&$auth_instance)"
.br
.ti -1c
.RI "\fBXortifyAuthCurlxmlProvisionning\fP (&$auth_instance)"
.br
.ti -1c
.RI "\fBgetXortifyUser\fP ($uname)"
.br
.ti -1c
.RI "\fBsync\fP ($datas, $uname, $pwd=null)"
.br
.ti -1c
.RI "\fBadd\fP ($datas, $uname, $pwd=null)"
.br
.ti -1c
.RI "\fBchange\fP (&$xoopsUser, $datas, $uname, $pwd=null)"
.br
.ti -1c
.RI "\fBchange_curl\fP (&$xoopsUser, $datas, $uname, $pwd=null)"
.br
.ti -1c
.RI "\fBdelete\fP ()"
.br
.ti -1c
.RI "\fBsuspend\fP ()"
.br
.ti -1c
.RI "\fBrestore\fP ()"
.br
.ti -1c
.RI "\fBresetpwd\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$_auth_instance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file auth_curlxml_provisionning\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "add ($datas, $uname, $pwd = \fCnull\fP)"
Add a new user to the system
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 101 of file auth_curlxml_provisionning\&.php\&.
.SS "change (&$xoopsUser, $datas, $uname, $pwd = \fCnull\fP)"
Modify user information
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 145 of file auth_curlxml_provisionning\&.php\&.
.SS "delete ()"
Modify a user
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 182 of file auth_curlxml_provisionning\&.php\&.
.SS "getXortifyUser ($uname)"
Return a Xortify User Object
.PP
\fBReturns:\fP
.RS 4
XortifyUser or false 
.RE
.PP

.PP
Definition at line 70 of file auth_curlxml_provisionning\&.php\&.
.SS "resetpwd ()"
Add a new user to the system
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 206 of file auth_curlxml_provisionning\&.php\&.
.SS "restore ()"
Restore a user
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 198 of file auth_curlxml_provisionning\&.php\&.
.SS "suspend ()"
Suspend a user
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 190 of file auth_curlxml_provisionning\&.php\&.
.SS "sync ($datas, $uname, $pwd = \fCnull\fP)"
Launch the synchronisation process
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 84 of file auth_curlxml_provisionning\&.php\&.
.SS "\fBXortifyAuthCurlxmlProvisionning\fP (&$auth_instance)"
Authentication Service constructor 
.PP
Definition at line 51 of file auth_curlxml_provisionning\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
