.TH "XortifyLog" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XortifyLog \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits XoopsObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXortifyLog\fP ($id=null)"
.br
.ti -1c
.RI "\fBtoArray\fP ()"
.br
.ti -1c
.RI "\fBrunPrePlugin\fP ($default=true)"
.br
.ti -1c
.RI "\fBrunPostPlugin\fP ($lid)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file log\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
