.TH "XortifyAuthFactory" 3 "Tue Jul 23 2013" "Version 4.11" "Xortify Honeypot Cloud Services" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XortifyAuthFactory \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "& \fBgetAuthConnection\fP ($uname, $xortify_auth_method= 'soap')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file authfactory\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "& getAuthConnection ($uname, $xortify_auth_method = \fC'soap'\fP)\fC [static]\fP"
Get a reference to the only instance of authentication class
.PP
if the class has not been instantiated yet, this will also take care of that
.PP
\fBReturns:\fP
.RS 4
object Reference to the only instance of authentication class 
.RE
.PP

.PP
Definition at line 44 of file authfactory\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot Cloud Services from the source code\&.
