.TH "Q:/@websites@/coop/labs/dev2/class/auth/auth_soap_provisionning.php" 3 "Wed Jul 17 2013" "Version 4.11" "Xortify Honeypot PHP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Q:/@websites@/coop/labs/dev2/class/auth/auth_soap_provisionning.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBXortifyAuthSoapProvisionning\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot PHP Library from the source code\&.
