.TH "Q:/@websites@/coop/labs/dev2/class/auth/auth_wgetxml.php" 3 "Wed Jul 17 2013" "Version 4.11" "Xortify Honeypot PHP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Q:/@websites@/coop/labs/dev2/class/auth/auth_wgetxml.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBXortifyAuthWgetxml\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP(!defined('XORTIFY_WGETXML_API')) 
.br
define('XORTIFY_WGETXML_API' \fB_RUN_XORTIFY_API_XML\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBif\fP (!defined('XORTIFY_WGETXML_API')) define('XORTIFY_WGETXML_API' _RUN_XORTIFY_API_XML"

.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot PHP Library from the source code\&.
