.TH "CacheModelObject" 3 "Wed Jul 17 2013" "Version 4.11" "Xortify Honeypot PHP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CacheModelObject \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCacheModelObject\fP ()"
.br
.ti -1c
.RI "\fB__construct\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBCacheModelObject\fP ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot PHP Library from the source code\&.
