.TH "CacheModelHandler" 3 "Wed Jul 17 2013" "Version 4.11" "Xortify Honeypot PHP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CacheModelHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits PersistableObjectHandler\&.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBTABLE\fP = 'cache_model'"
.br
.ti -1c
.RI "const \fBCLASSNAME\fP = '\fBCacheModelObject\fP'"
.br
.ti -1c
.RI "const \fBKEYNAME\fP = 'key'"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "const CLASSNAME = '\fBCacheModelObject\fP'"

.SS "const KEYNAME = 'key'"

.SS "const TABLE = 'cache_model'"


.SH "Author"
.PP 
Generated automatically by Doxygen for Xortify Honeypot PHP Library from the source code\&.
