.TH "Q:/@websites@/coop/labs/dev2/class/cache Directory Reference" 3 "Wed Jul 17 2013" "Version 4.11" "Xortify Honeypot PHP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Q:/@websites@/coop/labs/dev2/class/cache Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBapc\&.php\fP"
.br
.ti -1c
.RI "file \fBcache\&.php\fP"
.br
.ti -1c
.RI "file \fBfile\&.php\fP"
.br
.ti -1c
.RI "file \fBmemcache\&.php\fP"
.br
.ti -1c
.RI "file \fBmodel\&.php\fP"
.br
.ti -1c
.RI "file \fBxcache\&.php\fP"
.br
.in -1c
